import { existsSync } from "node:fs";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as p from "@clack/prompts";
import type { Command } from "commander";
import pc from "picocolors";
import { detectModels } from "../utils/detect-models";

/**
 * `flowpanel scaffold <Model>` — generate a resource() config stub for a model.
 */
export function scaffoldCommand(cli: Command): void {
  cli
    .command("scaffold [model]")
    .description("Generate a resource config stub")
    .option("--fields <list>", "Comma-separated field names")
    .option("--force", "Overwrite existing file")
    .addHelpText("after", "\n  Example:\n    flowpanel scaffold User --fields email,name,createdAt")
    .action(async (model: string | undefined, options: { fields?: string; force?: boolean }) => {
      p.intro(`Scaffolding resource${model ? `: ${pc.bold(model)}` : ""}`);

      const cwd = process.cwd();
      const detected = await detectModels(cwd);

      let selected = model;

      if (!selected) {
        if (!detected.schemaPath || detected.models.length === 0) {
          p.cancel(
            pc.red("No Prisma or Drizzle schema found.\n") +
              pc.dim("Run `flowpanel init` first or create a schema."),
          );
          process.exit(1);
        }

        const answer = await p.select({
          message: "Which model to scaffold?",
          options: detected.models.map((m) => ({ label: m, value: m })),
        });
        if (p.isCancel(answer)) {
          p.cancel("Aborted.");
          process.exit(0);
        }
        selected = answer as string;
      }

      if (!selected) {
        p.cancel(pc.red("No model specified."));
        process.exit(1);
      }

      // Validate against schema if we have one (skip if model passed via CLI arg directly)
      if (detected.models.length > 0 && !detected.models.includes(selected)) {
        p.log.warn(
          `Model "${selected}" not found in schema. Available: ${detected.models.join(", ")}`,
        );
      }

      const resourceName = camelLowerFirst(selected);
      const outPath = `src/flowpanel/resources/${resourceName}.ts`;
      const outFile = path.join(cwd, outPath);

      if (existsSync(outFile) && !options.force) {
        p.cancel(`${outPath} already exists. Use ${pc.cyan("--force")} to overwrite.`);
        process.exit(1);
      }

      const fields = options.fields
        ? options.fields
            .split(",")
            .map((f) => f.trim())
            .filter(Boolean)
        : null;

      const stub = renderStub(selected, detected.source === "drizzle", fields);
      await fs.mkdir(path.dirname(outFile), { recursive: true });
      await fs.writeFile(outFile, stub, "utf-8");

      p.log.success(`Created ${outPath}`);
      p.log.info(
        `Next steps:\n` +
          `  • Import it in your flowpanel.config.ts\n` +
          `  • Add to resources: { ${resourceName}: ${resourceName}Resource }`,
      );

      p.outro(pc.green(`✓ Created ${outPath}`));
    });
}

function camelLowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function renderStub(modelName: string, isDrizzle: boolean, fields: string[] | null): string {
  const resourceName = camelLowerFirst(modelName);
  const modelImport = isDrizzle ? `${resourceName} as ${resourceName}Table` : modelName;
  const resourceTarget = isDrizzle ? `${resourceName}Table` : `prisma.${resourceName}`;
  const importLine = isDrizzle
    ? `import { ${modelImport} } from "../../drizzle/schema";`
    : `import { prisma } from "../../lib/prisma";`;

  const columnsBody =
    fields && fields.length > 0
      ? fields.map((f) => `    (p) => p.${f},`).join("\n")
      : `    (p) => p.id,\n    // (p) => p.name,\n    // (p) => p.createdAt,`;

  return `/**
 * FlowPanel resource for ${modelName}.
 * Generated by \`flowpanel scaffold ${modelName}\`.
 *
 * Wire this up in flowpanel.config.ts:
 *   import { ${resourceName}Resource } from "./flowpanel/resources/${resourceName}";
 *   resources: { ${resourceName}: ${resourceName}Resource }
 */
import { resource } from "@flowpanel/core";
${importLine}

export const ${resourceName}Resource = resource(${resourceTarget}, {
  // label: "${modelName}",                 // override display label
  // labelPlural: "${modelName}s",
  // defaultSort: { field: "createdAt", dir: "desc" },

  // Columns (shorthand): array of path functions
  columns: [
${columnsBody}
  ],

  // Filters (shorthand)
  // filters: [(p) => p.status],

  // Actions
  // actions: (a) => ({
  //   archive: a.mutation({
  //     label: "Archive",
  //     confirm: "Archive this ${resourceName}?",
  //     handler: async (row, ctx) => {
  //       await ctx.db.${resourceName}.update({ where: { id: row.id }, data: { archived: true } });
  //     },
  //   }),
  //   exportCsv: a.collection({
  //     label: "Export CSV",
  //     handler: async (ctx) => {
  //       const rows = await ctx.db.${resourceName}.findMany();
  //       return {
  //         download: {
  //           filename: "${resourceName}.csv",
  //           content: rows.map(r => Object.values(r).join(",")).join("\\n"),
  //           mimeType: "text/csv",
  //         },
  //       };
  //     },
  //   }),
  // }),

  // access: {
  //   list: true,
  //   create: ["admin"],
  //   update: ["admin"],
  //   delete: ["admin"],
  // },
});
`;
}
