import * as fs from "node:fs/promises";
import * as path from "node:path";
import kleur from "kleur";
import prompts from "prompts";
import { detectModels } from "../utils/detect-models";
import { formatSuccess } from "../utils/error-format";

/**
 * `flowpanel scaffold <modelName>` — generate a resource() config stub for a model
 * in the user's project. Detects Prisma or Drizzle and writes to
 * `flowpanel/<resourceName>.ts`.
 */
export async function runScaffold(
  modelName: string | undefined,
  cwd: string = process.cwd(),
): Promise<void> {
  const detected = await detectModels(cwd);
  if (!detected.schemaPath || detected.models.length === 0) {
    console.error(kleur.red("  ✗ No Prisma or Drizzle schema found."));
    console.error(kleur.gray("  Run `flowpanel init` first or create a schema."));
    process.exit(1);
  }

  let selected = modelName;
  if (!selected) {
    const { model } = await prompts({
      type: "select",
      name: "model",
      message: "Which model to scaffold?",
      choices: detected.models.map((m) => ({ title: m, value: m })),
    });
    selected = model;
  }

  if (!selected) {
    console.error(kleur.red("  ✗ No model specified."));
    process.exit(1);
  }

  if (!detected.models.includes(selected)) {
    console.error(
      kleur.red(
        `  ✗ Model "${selected}" not found in ${detected.schemaPath}. Available: ${detected.models.join(", ")}`,
      ),
    );
    process.exit(1);
  }

  const resourceName = camelLowerFirst(selected);
  const outDir = path.join(cwd, "flowpanel", "resources");
  await fs.mkdir(outDir, { recursive: true });
  const outFile = path.join(outDir, `${resourceName}.ts`);

  const stub = renderStub(selected, detected.source === "drizzle");
  await fs.writeFile(outFile, stub, "utf-8");

  console.log(formatSuccess(`Created  ${path.relative(cwd, outFile)}`));
  console.log(kleur.gray("\n  Next steps:"));
  console.log(kleur.gray(`    • Import it in your flowpanel.config.ts`));
  console.log(
    kleur.gray(`    • Add to the resources map: { ${resourceName}: ${resourceName}Resource }`),
  );
  console.log(kleur.gray(`    • Re-run \`flowpanel dev\` to see the new tab`));
}

function camelLowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function renderStub(modelName: string, isDrizzle: boolean): string {
  const resourceName = camelLowerFirst(modelName);
  const modelImport = isDrizzle ? `${resourceName} as ${resourceName}Table` : modelName;
  const resourceTarget = isDrizzle ? `${resourceName}Table` : `prisma.${resourceName}`;
  const importLine = isDrizzle
    ? `import { ${modelImport} } from "../../drizzle/schema";`
    : `import { prisma } from "../../lib/prisma";`;

  return `/**
 * FlowPanel resource for ${modelName}.
 * Generated by \`flowpanel scaffold ${modelName}\`.
 *
 * Wire this up in flowpanel.config.ts:
 *   import { ${resourceName}Resource } from "./flowpanel/resources/${resourceName}";
 *   resources: { ${resourceName}: ${resourceName}Resource }
 */
import { resource } from "@flowpanel/core";
${importLine}

export const ${resourceName}Resource = resource(${resourceTarget}, {
  // label: "${modelName}",                 // override display label
  // labelPlural: "${modelName}s",
  // defaultSort: { field: "createdAt", dir: "desc" },

  // Columns (shorthand): array of path functions
  columns: [
    (p) => p.id,
    // (p) => p.name,
    // (p) => p.createdAt,
  ],

  // Filters (shorthand)
  // filters: [(p) => p.status],

  // Actions
  // actions: (a) => ({
  //   archive: a.mutation({
  //     label: "Archive",
  //     confirm: "Archive this ${resourceName}?",
  //     handler: async (row, ctx) => {
  //       await ctx.db.${resourceName}.update({ where: { id: row.id }, data: { archived: true } });
  //     },
  //   }),
  //   exportCsv: a.collection({
  //     label: "Export CSV",
  //     handler: async (ctx) => {
  //       const rows = await ctx.db.${resourceName}.findMany();
  //       return {
  //         download: {
  //           filename: "${resourceName}.csv",
  //           content: rows.map(r => Object.values(r).join(",")).join("\\n"),
  //           mimeType: "text/csv",
  //         },
  //       };
  //     },
  //   }),
  // }),

  // access: {
  //   list: true,
  //   create: ["admin"],
  //   update: ["admin"],
  //   delete: ["admin"],
  // },
});
`;
}
