import type { ModelMetadata } from "@flowpanel/core";
import { describe, expect, it } from "vitest";
import { prismaBridge } from "../typed";

describe("prismaBridge (typed builder)", () => {
  it("maps a registered delegate to its ModelMetadata", () => {
    const userDelegate = { findMany: () => [] };
    const metadata: ModelMetadata = {
      name: "User",
      primaryKey: "id",
      fields: [
        {
          name: "id",
          type: "int",
          kind: "scalar",
          isRequired: true,
          isList: false,
          isId: true,
          isAutoGenerated: true,
        },
      ],
    };
    const models = new Map([["User", metadata]]);
    const prismaStub = { user: userDelegate };

    prismaBridge.register(prismaStub as Record<string, unknown>, models);

    expect(prismaBridge.inferMetadata(userDelegate)).toBe(metadata);
  });

  it("throws a helpful error when the delegate is unknown", () => {
    expect(() => prismaBridge.inferMetadata({})).toThrow(/could not map this Prisma delegate/);
  });

  it("rejects non-object delegates", () => {
    expect(() => prismaBridge.inferMetadata("user" as unknown)).toThrow(
      /expected a Prisma delegate object/,
    );
  });
});
