/**
 * Resource Resolver — converts a ResourceDescriptor into a ResolvedResource
 * using ModelMetadata from the ORM adapter.
 */

import { resolvePathStrings, type PathProxy } from "./path";
import {
  createColumnBuilder,
  createFilterBuilder,
  createActionBuilder,
  resolveShorthandColumns,
  resolveShorthandFilters,
  titleCase,
  lastSegment,
} from "./builders";
import type {
  ModelMetadata,
  PathFn,
  ResolvedAction,
  ResolvedColumn,
  ResolvedFilter,
  ResolvedResource,
  ResourceDescriptor,
  ResourceOptions,
  Row,
} from "./types";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const RESERVED_ACTION_IDS = new Set(["list", "read", "create", "update", "delete"]);

// ---------------------------------------------------------------------------
// createResourceDescriptor
// ---------------------------------------------------------------------------

/**
 * Factory for ResourceDescriptor. The first arg is an opaque model reference
 * (Prisma delegate, Drizzle table, or string model name). Second arg is optional
 * ResourceOptions.
 */
export function createResourceDescriptor<TRow = Row>(
  modelRef: unknown,
  opts: ResourceOptions<TRow> = {},
): ResourceDescriptor<TRow> {
  return {
    __brand: "flowpanel.resource",
    modelRef,
    opts,
  };
}

// ---------------------------------------------------------------------------
// Label helpers
// ---------------------------------------------------------------------------

/**
 * Pluralize an English word using common rules. Handles the main cases admin
 * UIs encounter; for irregular plurals, pass `labelPlural` explicitly.
 *
 * Rules:
 * - consonant + y → ies (Company → Companies), but vowel + y → +s (Day → Days)
 * - ends in s/x/z/ch/sh → +es (Status → Statuses, Box → Boxes, Match → Matches)
 * - consonant + o → +es (Hero → Heroes), but vowel + o → +s (Studio → Studios)
 * - ends in f/fe → ves (Leaf → Leaves, Knife → Knives)
 * - otherwise → +s
 */
function pluralize(word: string): string {
  if (!word) return word;
  const lower = word.toLowerCase();

  // f / fe → ves (Leaf → Leaves, Knife → Knives)
  if (lower.endsWith("fe")) return word.slice(0, -2) + "ves";
  if (lower.endsWith("f") && !lower.endsWith("ff")) return word.slice(0, -1) + "ves";

  // consonant + y → ies (Category → Categories)
  if (lower.endsWith("y") && lower.length >= 2 && !isVowel(lower[lower.length - 2]!)) {
    return word.slice(0, -1) + "ies";
  }

  // s / x / z / ch / sh → es
  if (/(s|x|z|ch|sh)$/i.test(lower)) {
    return word + "es";
  }

  // consonant + o → oes (Hero → Heroes); vowel + o → os (Studio → Studios)
  if (lower.endsWith("o") && lower.length >= 2 && !isVowel(lower[lower.length - 2]!)) {
    return word + "es";
  }

  return word + "s";
}

function isVowel(ch: string): boolean {
  return ch === "a" || ch === "e" || ch === "i" || ch === "o" || ch === "u";
}

// ---------------------------------------------------------------------------
// Auto-column / filter / search helpers
// ---------------------------------------------------------------------------

function autoColumns(metadata: ModelMetadata): ResolvedColumn[] {
  const c = createColumnBuilder<Row>();
  return metadata.fields
    .filter(
      (f) =>
        !f.isAutoGenerated && f.kind !== "relation" && (f.kind === "scalar" || f.kind === "enum"),
    )
    .map((f) => c.field((p: PathProxy<Row>) => p[f.name] as unknown as never));
}

function autoFilters(metadata: ModelMetadata): ResolvedFilter[] {
  const f = createFilterBuilder<Row>();
  return metadata.fields
    .filter((field) => field.kind === "enum" || field.type === "boolean")
    .map((field) => f.filter((p: PathProxy<Row>) => p[field.name] as unknown as never));
}

function autoSearchFields(metadata: ModelMetadata): string[] {
  return metadata.fields
    .filter((f) => f.kind === "scalar" && f.type === "string")
    .map((f) => f.name);
}

// ---------------------------------------------------------------------------
// inferIncludeFromPaths
// ---------------------------------------------------------------------------

/**
 * Converts dot-paths to a Prisma-style include tree.
 *
 * Examples:
 *   ["email"]                  → {}
 *   ["user.email"]             → { user: true }
 *   ["user.subscription.planId"] → { user: { include: { subscription: true } } }
 *   ["_count.posts"]           → {}
 */
export function inferIncludeFromPaths(paths: string[]): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const path of paths) {
    const segments = path.split(".");
    if (segments.length < 2) {
      // Scalar — no include needed
      continue;
    }

    const [first, ...rest] = segments;

    // Skip _count
    if (first === "_count") {
      continue;
    }

    // Single-level relation: ["user", "email"] → user: true
    if (rest.length === 1) {
      // Only set to true if not already a nested include (manual wins via mergeIncludes)
      if (result[first] === undefined) {
        result[first] = true;
      }
      // If it's already an object include, keep it (more specific)
      continue;
    }

    // Nested relation: ["user", "subscription", "planId"]
    // We need user: { include: { subscription: true } }
    const relationSegments = rest.slice(0, -1); // all but the leaf field

    // Build or merge nested include
    let current = result;
    let currentKey = first;

    for (let i = 0; i < relationSegments.length; i++) {
      const relationName = relationSegments[i];

      if (current[currentKey] === undefined || current[currentKey] === true) {
        // Upgrade from true → nested include object
        current[currentKey] = { include: {} };
      }

      const node = current[currentKey] as { include: Record<string, unknown> };
      if (!node.include) {
        node.include = {};
      }

      if (i === relationSegments.length - 1) {
        // Last relation segment — set to true if not already nested
        if (node.include[relationName] === undefined) {
          node.include[relationName] = true;
        }
      } else {
        if (node.include[relationName] === undefined || node.include[relationName] === true) {
          node.include[relationName] = { include: {} };
        }
        current = node.include;
        currentKey = relationName;
      }
    }
  }

  return result;
}

// ---------------------------------------------------------------------------
// mergeIncludes
// ---------------------------------------------------------------------------

/**
 * Deep merges inferred includes with manual includes. Manual wins on conflict.
 */
export function mergeIncludes(
  inferred: Record<string, unknown>,
  manual: Record<string, unknown> | undefined,
): Record<string, unknown> {
  if (!manual) return inferred;

  const result: Record<string, unknown> = { ...inferred };

  for (const [key, manualVal] of Object.entries(manual)) {
    // Manual always wins
    result[key] = manualVal;
  }

  return result;
}

// ---------------------------------------------------------------------------
// resolveResource
// ---------------------------------------------------------------------------

/**
 * Processes a ResourceDescriptor with ModelMetadata to produce a ResolvedResource.
 *
 * The generic `TRow` exists purely to accept typed descriptors from user code;
 * internally everything is erased to `Row` because ModelMetadata is runtime data.
 */
export function resolveResource<TRow = Row>(
  key: string,
  descriptor: ResourceDescriptor<TRow>,
  metadata: ModelMetadata,
): ResolvedResource {
  const opts: ResourceOptions<TRow> = descriptor.opts ?? {};

  // ---- Label ----------------------------------------------------------------
  const modelName = metadata.name;
  let label: string;
  let labelPlural: string;

  if (opts.label) {
    label = opts.label;
    labelPlural = opts.labelPlural ?? pluralize(opts.label);
  } else {
    label = titleCase(modelName);
    labelPlural = opts.labelPlural ?? pluralize(label);
  }

  // ---- Columns --------------------------------------------------------------
  let columns: ResolvedColumn[];
  if (Array.isArray(opts.columns)) {
    // Shorthand: array of PathFns
    columns = resolveShorthandColumns(opts.columns as PathFn<TRow>[]);
  } else if (typeof opts.columns === "function") {
    columns = opts.columns(createColumnBuilder<TRow>());
  } else {
    columns = autoColumns(metadata);
  }

  // ---- Filters --------------------------------------------------------------
  let filters: ResolvedFilter[];
  if (Array.isArray(opts.filters)) {
    filters = resolveShorthandFilters(opts.filters as PathFn<TRow>[]);
  } else if (typeof opts.filters === "function") {
    filters = opts.filters(createFilterBuilder<TRow>());
  } else {
    filters = autoFilters(metadata);
  }

  // ---- Search ---------------------------------------------------------------
  let searchFields: string[];
  if (opts.searchFields) {
    searchFields = resolvePathStrings(opts.searchFields as PathFn<TRow>[]);
  } else {
    searchFields = autoSearchFields(metadata);
  }

  // ---- Actions --------------------------------------------------------------
  let actions: ResolvedAction[] = [];
  if (opts.actions) {
    const raw = opts.actions(createActionBuilder<TRow>());

    // Support both Record<string, ResolvedAction> (keyed) and array forms
    if (Array.isArray(raw)) {
      actions = raw;
    } else {
      actions = Object.entries(raw).map(([actionId, action]) => ({
        ...action,
        id: actionId,
      }));
    }

    // Validate reserved IDs
    for (const action of actions) {
      if (RESERVED_ACTION_IDS.has(action.id)) {
        throw new Error(
          `Action id "${action.id}" is reserved. Reserved IDs are: ${[...RESERVED_ACTION_IDS].join(", ")}. Use a custom action id.`,
        );
      }
    }
  }

  // ---- Include inference ----------------------------------------------------
  const columnPaths = columns.filter((c) => c.path !== null).map((c) => c.path as string);
  const filterPaths = filters.map((f) => f.path);
  const allPaths = [...columnPaths, ...filterPaths, ...searchFields];

  const inferredInclude = inferIncludeFromPaths(allPaths);
  const include = mergeIncludes(inferredInclude, opts.include);
  const finalInclude = Object.keys(include).length > 0 ? include : undefined;

  // ---- Default sort ---------------------------------------------------------
  const defaultSort = opts.defaultSort ?? { field: metadata.primaryKey, dir: "desc" as const };

  // ---- Server-side maps -----------------------------------------------------
  const _handlers: Record<string, (row: Row, ctx: unknown) => Promise<unknown>> = {};
  const _computes: Record<string, (row: Row) => unknown> = {};
  const _whens: Record<string, (row: Row) => boolean> = {};

  for (const action of actions) {
    _handlers[action.id] = action.handler;
    if (action.when) {
      _whens[action.id] = action.when;
    }
  }

  for (const col of columns) {
    if (col.compute) {
      _computes[col.id] = col.compute;
    }
  }

  return {
    id: key,
    modelName,
    primaryKey: metadata.primaryKey,
    label,
    labelPlural,
    icon: opts.icon ?? "file-text",
    path: opts.path ?? key,
    defaultSort,
    defaultPageSize: opts.defaultPageSize ?? 50,
    searchFields,
    columns,
    filters,
    actions,
    access: opts.access ?? {},
    fieldAccess: opts.fieldAccess ?? [],
    include: finalInclude,
    readOnly: opts.readOnly,
    _handlers,
    _computes,
    _whens,
  };
}
