/**
 * Resource Type System — all TypeScript interfaces and types for the resource module.
 * This is a types-only file; no runtime code.
 */

import type { Path, PathFn } from "./path";

// Re-export path types for convenience
export type { Path, PathFn };

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/** Generic row type used as the default throughout the resource system. */
export type Row = Record<string, unknown>;

// ---------------------------------------------------------------------------
// Model Metadata (from DMMF / Drizzle introspection)
// ---------------------------------------------------------------------------

export interface FieldMetadata {
  name: string;
  type: "string" | "int" | "float" | "boolean" | "datetime" | "json" | "enum" | "relation";
  kind: "scalar" | "relation" | "enum";
  isRequired: boolean;
  isList: boolean;
  isId: boolean;
  /** True for auto-generated fields like id, createdAt, updatedAt. */
  isAutoGenerated: boolean;
  enumValues?: string[];
  /** Target model name for relation fields. */
  relationModel?: string;
  default?: unknown;
}

export interface ModelMetadata {
  /** e.g. "User", "Post" */
  name: string;
  /** SQL table name if different from the model name. */
  tableName?: string;
  fields: FieldMetadata[];
  /** Primary key field name, usually "id". */
  primaryKey: string;
}

// ---------------------------------------------------------------------------
// Normalized Filter IR (adapter-agnostic)
// ---------------------------------------------------------------------------

export type FilterOp =
  | "eq"
  | "neq"
  | "contains"
  | "startsWith"
  | "endsWith"
  | "in"
  | "notIn"
  | "gte"
  | "lte"
  | "gt"
  | "lt"
  | "isNull"
  | "isNotNull";

export interface NormalizedFilter {
  /** Dot-path like "user.email" or "status". */
  field: string;
  op: FilterOp;
  value: unknown;
}

// ---------------------------------------------------------------------------
// Resource Adapter (abstract contract between core and ORM adapters)
// ---------------------------------------------------------------------------

export interface FindManyArgs {
  where?: NormalizedFilter[];
  /** Search filters combined with OR semantics (separate from regular AND filters). */
  searchOr?: NormalizedFilter[];
  orderBy?: { field: string; dir: "asc" | "desc" };
  skip?: number;
  take?: number;
  include?: Record<string, unknown>;
}

export interface ResourceAdapter {
  findMany(model: string, args: FindManyArgs): Promise<{ data: Row[]; total: number }>;
  findUnique(
    model: string,
    args: { where: Record<string, unknown>; include?: Record<string, unknown> },
  ): Promise<Row | null>;
  count(model: string, args: { where?: NormalizedFilter[] }): Promise<number>;
  create(model: string, args: { data: Record<string, unknown> }): Promise<Row>;
  update(
    model: string,
    args: { where: Record<string, unknown>; data: Record<string, unknown> },
  ): Promise<Row>;
  delete(model: string, args: { where: Record<string, unknown> }): Promise<Row>;
  getModelMetadata(model: string): ModelMetadata;
  getEnumValues(enumName: string): string[];
  getModelNames(): string[];
}

// ---------------------------------------------------------------------------
// Column Types
// ---------------------------------------------------------------------------

export type ColumnFormat =
  | "text"
  | "money"
  | "number"
  | "percent"
  | "image"
  | "relative"
  | "absolute"
  | "calendar"
  | "tags"
  | "link"
  | "json"
  | "boolean"
  | "enum"
  | "duration";

export interface FieldColumnOpts {
  label?: string;
  width?: number;
  flex?: number;
  format?: ColumnFormat;
  pin?: "left" | "right";
  /** Controls in which views the column is visible. */
  visible?: "list" | "detail" | "always";
  sortable?: boolean;
  searchable?: boolean;
  mono?: boolean;
  align?: "left" | "center" | "right";
  href?: (row: Row) => string;
}

export interface ResolvedColumn {
  id: string;
  /** Null for computed or custom columns. */
  path: string | null;
  label: string;
  type: "field" | "computed" | "custom";
  format: ColumnFormat | "auto";
  opts: FieldColumnOpts;
  compute?: (row: Row) => unknown;
  /** React component reference. */
  render?: unknown;
  sortExpr?: unknown;
}

// ---------------------------------------------------------------------------
// Filter Types
// ---------------------------------------------------------------------------

export type FilterMode =
  | "enum"
  | "multiselect"
  | "text"
  | "number"
  | "range"
  | "dateRange"
  | "boolean"
  | "relation";

export interface FilterOpts {
  mode?: FilterMode;
  label?: string;
  debounceMs?: number;
  options?: string[];
}

export interface ResolvedFilter {
  id: string;
  path: string;
  label: string;
  mode: FilterMode | "auto";
  opts: FilterOpts;
  toWhere?: (value: unknown) => Record<string, unknown>;
  /** React component reference. */
  render?: unknown;
}

// ---------------------------------------------------------------------------
// Action Types
// ---------------------------------------------------------------------------

export interface ConfirmConfig {
  title?: string;
  description?: string | ((row: Row) => string);
  intent?: "default" | "destructive";
  /** Whether to require a step-up authentication before proceeding. */
  stepUp?: boolean;
  /** Require the user to type this string to confirm. */
  typeToConfirm?: string;
  confirmLabel?: string;
}

export interface MutationActionConfig<TRow, TCtx> {
  label: string;
  /** Icon identifier string. */
  icon?: string;
  variant?: "default" | "danger";
  confirm?: string | ConfirmConfig;
  when?: (row: TRow) => boolean;
  handler: (row: TRow, ctx: TCtx) => Promise<void | Partial<TRow>>;
  onSuccess?: { toast?: string; invalidate?: string[] };
  rateLimit?: { perMinute?: number; perHour?: number };
}

export interface ResolvedAction {
  id: string;
  type: "mutation";
  label: string;
  /** Icon identifier string. */
  icon?: string;
  variant: "default" | "danger";
  confirm?: ConfirmConfig;
  when?: (row: Row) => boolean;
  handler: (row: Row, ctx: unknown) => Promise<unknown>;
  onSuccess?: { toast?: string; invalidate?: string[] };
}

// ---------------------------------------------------------------------------
// Access Types
// ---------------------------------------------------------------------------

/** False = deny all. String array = role allowlist. Function = dynamic rule. */
export type AccessRule = false | string[] | ((ctx: unknown, row?: Row) => boolean);

export interface AccessConfig {
  list?: AccessRule;
  read?: AccessRule;
  create?: AccessRule;
  update?: AccessRule;
  delete?: AccessRule;
  /** Additional per-action access rules keyed by action id. */
  [actionId: string]: AccessRule | undefined;
}

export interface FieldAccessRule {
  path: string;
  read?: AccessRule;
  write?: AccessRule;
}

// ---------------------------------------------------------------------------
// Builder Options (for computed / custom columns and filters)
// ---------------------------------------------------------------------------

export interface ComputedColumnOpts<TRow> {
  label: string;
  format?: ColumnFormat;
  compute: (row: TRow) => unknown;
  /** React component reference. */
  render?: unknown;
  sortExpr?: unknown;
  opts?: Omit<FieldColumnOpts, "label" | "format">;
}

export interface CustomColumnOpts {
  id: string;
  label: string;
  /** React component reference. */
  render: unknown;
  format?: ColumnFormat;
  opts?: Omit<FieldColumnOpts, "label" | "format">;
}

export interface CustomFilterOpts {
  id: string;
  label: string;
  mode: FilterMode;
  toWhere?: (value: unknown) => Record<string, unknown>;
  /** React component reference. */
  render?: unknown;
  opts?: FilterOpts;
}

// ---------------------------------------------------------------------------
// Builder Interfaces
// ---------------------------------------------------------------------------

export interface ColumnBuilder<TRow> {
  field(path: PathFn<TRow>, opts?: FieldColumnOpts): ResolvedColumn;
  computed(name: string, opts: ComputedColumnOpts<TRow>): ResolvedColumn;
  custom(opts: CustomColumnOpts): ResolvedColumn;
}

export interface FilterBuilder<TRow> {
  filter(path: PathFn<TRow>, opts?: FilterOpts): ResolvedFilter;
  custom(opts: CustomFilterOpts): ResolvedFilter;
}

export interface ActionBuilder<TRow> {
  mutation(config: MutationActionConfig<TRow, unknown>): ResolvedAction;
}

// ---------------------------------------------------------------------------
// Resource Options (§5.2)
// ---------------------------------------------------------------------------

export interface ResourceOptions<TRow = Row> {
  /** Display label for this resource, e.g. "Users". */
  label?: string;
  /** Plural label, e.g. "Users" (defaults to label). */
  labelPlural?: string;
  /** Icon identifier string. */
  icon?: string;
  /** Default sort applied to list queries. */
  defaultSort?: { field: string; dir: "asc" | "desc" };
  /** Default number of rows per page. */
  defaultPageSize?: number;
  /** Fields to include in full-text search. */
  searchFields?: PathFn<TRow>[];
  /** Column definitions — shorthand PathFn[] or builder function. */
  columns?: PathFn<TRow>[] | ((builder: ColumnBuilder<TRow>) => ResolvedColumn[]);
  /** Filter definitions — shorthand PathFn[] or builder function. */
  filters?: PathFn<TRow>[] | ((builder: FilterBuilder<TRow>) => ResolvedFilter[]);
  /** Row-level actions. Return either a keyed record (keys → action IDs) or an array. */
  actions?: (builder: ActionBuilder<TRow>) => Record<string, ResolvedAction> | ResolvedAction[];
  /** Access control configuration. */
  access?: AccessConfig;
  /** Field-level access rules. */
  fieldAccess?: FieldAccessRule[];
  /** Relations to eagerly include. */
  include?: Record<string, unknown>;
  /** Navigation path segment, e.g. "users". Defaults to lowercase model name. */
  path?: string;
  /** When true, forces create/update/delete access to false regardless of roles. */
  readOnly?: boolean;
}

// ---------------------------------------------------------------------------
// Resource Descriptor
// ---------------------------------------------------------------------------

export interface ResourceDescriptor<TRow = Row> {
  readonly __brand: "flowpanel.resource";
  /** Opaque reference to the ORM model (e.g. Prisma model name or Drizzle table). */
  modelRef: unknown;
  opts: ResourceOptions<TRow>;
}

// ---------------------------------------------------------------------------
// Resolved Resource (server-side, ready for tRPC procedures)
// ---------------------------------------------------------------------------

export interface ResolvedResource {
  /** Unique resource identifier derived from the model name. */
  id: string;
  modelName: string;
  /** Primary key field name from model metadata. */
  primaryKey: string;
  label: string;
  labelPlural: string;
  icon?: string;
  path: string;
  defaultSort?: { field: string; dir: "asc" | "desc" };
  defaultPageSize: number;
  searchFields: string[];
  columns: ResolvedColumn[];
  filters: ResolvedFilter[];
  actions: ResolvedAction[];
  access: AccessConfig;
  fieldAccess: FieldAccessRule[];
  include?: Record<string, unknown>;
  readOnly?: boolean;
  /** Map of action id -> handler function for server-side lookup. */
  _handlers: Record<string, (row: Row, ctx: unknown) => Promise<unknown>>;
  /** Map of column id -> compute function for server-side lookup. */
  _computes: Record<string, (row: Row) => unknown>;
  /** Map of action id -> when predicate for server-side lookup. */
  _whens: Record<string, (row: Row) => boolean>;
}

// ---------------------------------------------------------------------------
// Serialized Resource (client-safe JSON, no functions)
// ---------------------------------------------------------------------------

/** Column descriptor safe to send to the client. */
export interface SerializedColumn {
  id: string;
  path: string | null;
  label: string;
  type: "field" | "computed" | "custom";
  format: ColumnFormat | "auto";
  opts: Omit<FieldColumnOpts, "href">;
  /** True when a client-side href function is present (not serialized). */
  hasHref?: boolean;
}

/** Filter descriptor safe to send to the client. */
export interface SerializedFilter {
  id: string;
  path: string;
  label: string;
  mode: FilterMode | "auto";
  opts: FilterOpts;
}

/** Action descriptor safe to send to the client. */
export interface SerializedAction {
  id: string;
  type: "mutation";
  label: string;
  icon?: string;
  variant: "default" | "danger";
  confirm?: ConfirmConfig;
  /** Access evaluated to boolean for the current session. */
  allowed: boolean;
  onSuccess?: { toast?: string; invalidate?: string[] };
}

/** Access evaluated to booleans for the current session. */
export interface SerializedAccess {
  list: boolean;
  read: boolean;
  create: boolean;
  update: boolean;
  delete: boolean;
  [actionId: string]: boolean;
}

/** Client-safe JSON representation of a resource. */
export interface SerializedResource {
  id: string;
  modelName: string;
  /** Primary key field name (e.g. "id", "uuid"). */
  primaryKey: string;
  label: string;
  labelPlural: string;
  icon?: string;
  path: string;
  defaultSort?: { field: string; dir: "asc" | "desc" };
  defaultPageSize: number;
  searchFields: string[];
  columns: SerializedColumn[];
  filters: SerializedFilter[];
  actions: SerializedAction[];
  access: SerializedAccess;
  fieldAccess: Array<{ path: string; read: boolean; write: boolean }>;
}
