import { rehypeCodeDefaultOptions } from "fumadocs-core/mdx-plugins";
import {
  defineCollections,
  defineConfig,
  defineDocs,
  frontmatterSchema,
} from "fumadocs-mdx/config";
import { transformerTwoslash } from "fumadocs-twoslash";
import { z } from "zod";

/**
 * Docs collection — file-based MDX with type-safe `title` / `description`
 * frontmatter (fumadocs' base schema). Drizzle/Prisma code samples switch
 * via the cookie-driven <AdapterTabs> component, not per-page frontmatter.
 */
export const docs = defineDocs({
  dir: "content/docs",
  docs: {
    schema: frontmatterSchema,
  },
});

export const blog = defineCollections({
  type: "doc",
  dir: "content/blog",
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    authors: z.array(z.string()).min(1),
    tags: z.array(z.string()).default([]),
    cover: z.string().optional(),
  }),
});

export const examples = defineCollections({
  type: "doc",
  dir: "content/examples",
  schema: z.object({
    title: z.string(),
    description: z.string(),
    repo: z.string().url(),
    stack: z.array(z.string()),
    cover: z.string().optional(),
  }),
});

/**
 * Changelog — generated by `scripts/aggregate-changelog.mjs` from every
 * `packages/*\/CHANGELOG.md`. Single `index.mdx`, rendered as the page
 * body on `/changelog`.
 */
export const changelog = defineCollections({
  type: "doc",
  dir: "content/changelog",
  schema: z.object({
    title: z.string(),
    description: z.string(),
  }),
});

export default defineConfig({
  mdxOptions: {
    // Highlighting handled by Fumadocs UI defaults (shiki). Code blocks
    // tagged ` ```ts twoslash ` are type-checked at build time and gain
    // inline type/hover popups — see `apps/site/ARCHITECTURE.md`.
    rehypeCodeOptions: {
      // Preserve Fumadocs' default transformers (notation highlight / diff /
      // focus / word) — a bare `transformers` array would otherwise replace
      // them via the shallow merge in `fumadocs-core`'s rehype-code plugin.
      // Spread the full defaults so required fields like `themes` are kept.
      ...rehypeCodeDefaultOptions,
      transformers: [...(rehypeCodeDefaultOptions.transformers ?? []), transformerTwoslash()],
    },
  },
});
