import {
  defineCollections,
  defineConfig,
  defineDocs,
  frontmatterSchema,
} from "fumadocs-mdx/config";
import { z } from "zod";

/**
 * Docs collection — file-based, type-safe frontmatter.
 *
 * `adapter` controls how code samples render on the page:
 *   - "both"          → page can use <AdapterTabs>; default
 *   - "prisma-only"   → only Prisma snippets, no tabs
 *   - "drizzle-only"  → only Drizzle snippets, no tabs
 */
export const docs = defineDocs({
  dir: "content/docs",
  docs: {
    schema: frontmatterSchema.extend({
      adapter: z.enum(["both", "prisma-only", "drizzle-only"]).default("both"),
      since: z
        .string()
        .regex(/^\d+\.\d+\.\d+$/, "expected semver like 0.7.2")
        .optional(),
      draft: z.boolean().default(false),
    }),
  },
});

export const blog = defineCollections({
  type: "doc",
  dir: "content/blog",
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    authors: z.array(z.string()).min(1),
    tags: z.array(z.string()).default([]),
    cover: z.string().optional(),
  }),
});

export const examples = defineCollections({
  type: "doc",
  dir: "content/examples",
  schema: z.object({
    title: z.string(),
    description: z.string(),
    repo: z.string().url(),
    stack: z.array(z.string()),
    cover: z.string().optional(),
  }),
});

/**
 * Changelog — generated by `scripts/aggregate-changelog.mjs` from every
 * `packages/*\/CHANGELOG.md`. Single `index.mdx`, rendered as the page
 * body on `/changelog`.
 */
export const changelog = defineCollections({
  type: "doc",
  dir: "content/changelog",
  schema: z.object({
    title: z.string(),
    description: z.string(),
  }),
});

export default defineConfig({
  mdxOptions: {
    // Highlighting handled by Fumadocs UI defaults (shiki).
  },
});
