import { relations } from "drizzle-orm";
import { integer, pgEnum, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";
import { describe, expect, it } from "vitest";
import { inferMetadata } from "../typed";

const plan = pgEnum("plan", ["free", "pro"]);

const users = pgTable("users", {
  id: serial("id").primaryKey(),
  email: text("email").notNull(),
  plan: plan("plan").notNull().default("free"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
});

const jobs = pgTable("jobs", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  categoryId: integer("category_id").references(() => categories.id),
});

const jobsRelations = relations(jobs, ({ one }) => ({
  category: one(categories, { fields: [jobs.categoryId], references: [categories.id] }),
}));

describe("inferMetadata (drizzle)", () => {
  it("extracts name, primaryKey, and scalar fields", () => {
    const meta = inferMetadata(users);
    expect(meta.name).toBe("users");
    expect(meta.primaryKey).toBe("id");
    expect(meta.fields.map((f) => f.name)).toEqual(["id", "email", "plan", "createdAt"]);
  });

  it("narrows enum values from pgEnum", () => {
    const meta = inferMetadata(users);
    const planField = meta.fields.find((f) => f.name === "plan");
    expect(planField?.enumValues).toEqual(["free", "pro"]);
    expect(planField?.type).toBe("enum");
    expect(planField?.kind).toBe("enum");
  });

  it("marks timestamp columns as datetime and auto-generated defaults", () => {
    const meta = inferMetadata(users);
    const ts = meta.fields.find((f) => f.name === "createdAt");
    expect(ts?.type).toBe("datetime");
    expect(ts?.isAutoGenerated).toBe(true);
  });

  it("marks serial primary key as int + auto", () => {
    const meta = inferMetadata(users);
    const id = meta.fields.find((f) => f.name === "id");
    expect(id?.type).toBe("int");
    expect(id?.isId).toBe(true);
    expect(id?.isAutoGenerated).toBe(true);
  });

  it("surfaces relations when given the full schema", () => {
    const schema = { jobs, categories, jobsRelations };
    const meta = inferMetadata(jobs, { schema });
    const rel = meta.fields.find((f) => f.name === "category");
    expect(rel).toBeDefined();
    expect(rel?.kind).toBe("relation");
    expect(rel?.relationModel).toBe("categories");
  });

  it("omits relations when no schema is provided", () => {
    const meta = inferMetadata(jobs);
    expect(meta.fields.find((f) => f.name === "category")).toBeUndefined();
  });
});
