import { describe, it, expect, vi } from "vitest";
import { createResourceProcedures } from "../../trpc/procedures/resources";
import type { ResolvedResource, ResourceAdapter, ModelMetadata, Row } from "../../resource/types";
import type { Session } from "../../types/config";

// Minimal tRPC double that just invokes handlers directly.
function makeTestTrpc() {
  const authedProcedure = {
    input: () => authedProcedure,
    query: (fn: unknown) => ({ _type: "query" as const, fn }),
    mutation: (fn: unknown) => ({ _type: "mutation" as const, fn }),
  };
  const t = {
    procedure: authedProcedure,
    router: (routes: Record<string, unknown>) => routes,
  };
  return { t, authedProcedure };
}

const metadata: ModelMetadata = {
  name: "Post",
  primaryKey: "id",
  fields: [
    {
      name: "id",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: true,
      isAutoGenerated: true,
    },
    {
      name: "title",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "orgId",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
  ],
};

function makeAdapter(rows: Row[]): ResourceAdapter {
  return {
    findMany: vi.fn(async (_m: string) => ({ data: rows, total: rows.length })),
    findUnique: vi.fn(async (_m: string, args: { where: Record<string, unknown> }) => {
      const id = args.where.id;
      return rows.find((r) => r.id === id) ?? null;
    }),
    create: vi.fn(async (_m: string, args: { data: Record<string, unknown> }) => ({
      id: "new",
      ...args.data,
    })),
    update: vi.fn(
      async (
        _m: string,
        args: { where: Record<string, unknown>; data: Record<string, unknown> },
      ) => ({
        ...(rows.find((r) => r.id === args.where.id) ?? {}),
        ...args.data,
      }),
    ),
    delete: vi.fn(
      async (_m: string, args: { where: Record<string, unknown> }) =>
        rows.find((r) => r.id === args.where.id) as Row,
    ),
    getModelMetadata: () => metadata,
    getEnumValues: () => [],
    getModelNames: () => ["Post"],
  };
}

function makeResolvedResource(): ResolvedResource {
  return {
    id: "posts",
    modelName: "Post",
    primaryKey: "id",
    label: "Post",
    labelPlural: "Posts",
    path: "posts",
    defaultPageSize: 50,
    searchFields: [],
    columns: [],
    filters: [],
    actions: [],
    access: {},
    fieldAccess: [],
    _handlers: {},
    _computes: {},
    _whens: {},
  };
}

const session: Session = { userId: "u1", role: "support" } as Session;

function makeCtx(
  rows: Row[],
  rowLevel?: (session: Session, ctx: Record<string, unknown>) => Record<string, unknown>,
) {
  const resource = makeResolvedResource();
  const adapter = makeAdapter(rows);
  // biome-ignore lint/suspicious/noExplicitAny: minimal test context
  const config: any = {
    security: rowLevel ? { rowLevel: { filter: rowLevel } } : undefined,
  };
  return {
    session,
    config,
    resources: { posts: resource },
    resourceAdapter: adapter,
    adapter,
  };
}

describe("rowLevel enforcement in resource procedures", () => {
  const rows: Row[] = [
    { id: "p1", title: "My post", orgId: "org-A" },
    { id: "p2", title: "Their post", orgId: "org-B" },
  ];

  it("list: filters rows to session's orgId", async () => {
    const { t, authedProcedure } = makeTestTrpc();
    const router = createResourceProcedures(t, authedProcedure) as Record<
      string,
      { fn: (args: unknown) => Promise<unknown> }
    >;
    const ctx = makeCtx(rows, (s) => ({ orgId: "org-A" }));

    const result = await router.list.fn({
      ctx,
      input: { resourceId: "posts", page: 1, pageSize: 50 },
    });

    // The adapter receives the rowLevel filter in the where clause
    expect((ctx.adapter.findMany as ReturnType<typeof vi.fn>).mock.calls[0]![0]).toBe("Post");
    const args = (ctx.adapter.findMany as ReturnType<typeof vi.fn>).mock.calls[0]![1];
    expect(args.where).toContainEqual({ field: "orgId", op: "eq", value: "org-A" });
    expect((result as { data: Row[] }).data.length).toBeGreaterThan(0);
  });

  it("get: returns 404 when row is outside scope", async () => {
    const { t, authedProcedure } = makeTestTrpc();
    const router = createResourceProcedures(t, authedProcedure) as Record<
      string,
      { fn: (args: unknown) => Promise<unknown> }
    >;
    const ctx = makeCtx(rows, () => ({ orgId: "org-A" }));

    await expect(
      router.get.fn({
        ctx,
        input: { resourceId: "posts", recordId: "p2" }, // p2 is org-B
      }),
    ).rejects.toThrow(/not found/i);
  });

  it("get: returns row when it matches scope", async () => {
    const { t, authedProcedure } = makeTestTrpc();
    const router = createResourceProcedures(t, authedProcedure) as Record<
      string,
      { fn: (args: unknown) => Promise<unknown> }
    >;
    const ctx = makeCtx(rows, () => ({ orgId: "org-A" }));

    const row = await router.get.fn({
      ctx,
      input: { resourceId: "posts", recordId: "p1" }, // p1 is org-A
    });

    expect((row as Row).id).toBe("p1");
  });

  it("update: blocks writes to rows outside scope", async () => {
    const { t, authedProcedure } = makeTestTrpc();
    const router = createResourceProcedures(t, authedProcedure) as Record<
      string,
      { fn: (args: unknown) => Promise<unknown> }
    >;
    const ctx = makeCtx(rows, () => ({ orgId: "org-A" }));

    await expect(
      router.update.fn({
        ctx,
        input: { resourceId: "posts", recordId: "p2", data: { title: "evil" } },
      }),
    ).rejects.toThrow(/not found/i);
    expect(ctx.adapter.update).not.toHaveBeenCalled();
  });

  it("delete: blocks deletes of rows outside scope", async () => {
    const { t, authedProcedure } = makeTestTrpc();
    const router = createResourceProcedures(t, authedProcedure) as Record<
      string,
      { fn: (args: unknown) => Promise<unknown> }
    >;
    const ctx = makeCtx(rows, () => ({ orgId: "org-A" }));

    await expect(
      router.delete.fn({
        ctx,
        input: { resourceId: "posts", recordId: "p2" },
      }),
    ).rejects.toThrow(/not found/i);
    expect(ctx.adapter.delete).not.toHaveBeenCalled();
  });

  it("create: injects rowLevel eq fields into written data", async () => {
    const { t, authedProcedure } = makeTestTrpc();
    const router = createResourceProcedures(t, authedProcedure) as Record<
      string,
      { fn: (args: unknown) => Promise<unknown> }
    >;
    const ctx = makeCtx(rows, () => ({ orgId: "org-A" }));

    await router.create.fn({
      ctx,
      input: { resourceId: "posts", data: { title: "new", orgId: "org-B" } }, // attempt to set org-B
    });

    const call = (ctx.adapter.create as ReturnType<typeof vi.fn>).mock.calls[0]![1];
    // orgId should be overwritten to the session's scope
    expect(call.data.orgId).toBe("org-A");
  });

  it("does nothing when rowLevel filter is absent", async () => {
    const { t, authedProcedure } = makeTestTrpc();
    const router = createResourceProcedures(t, authedProcedure) as Record<
      string,
      { fn: (args: unknown) => Promise<unknown> }
    >;
    const ctx = makeCtx(rows); // no rowLevel

    const row = await router.get.fn({
      ctx,
      input: { resourceId: "posts", recordId: "p2" },
    });
    expect((row as Row).id).toBe("p2");
  });
});
