import { resource } from "@flowpanel/kit";
import * as schema from "@/src/db/schema";
import { SITES } from "@/src/lib/catalog";
import { badge, formatDate, money, ratingCell } from "../format";

export const listings = resource(schema.listings, {
  label: "Listings",
  labelOne: "Listing",
  // Machine-generated by runs, so `create` is disabled below.
  columns: [
    { field: "title", label: "Product" },
    { field: "site", label: "Site", format: "badge" },
    { field: "priceCents", label: "Price", align: "right", format: money },
    { field: "stock", label: "Stock", format: badge },
    { field: "rating", label: "Rating", align: "right", render: (l) => ratingCell(l.rating) },
    { field: "reviews", label: "Reviews", align: "right", format: "number" },
    { field: "scrapedAt", label: "Scraped", render: (l) => formatDate(l.scrapedAt) },
  ],
  search: ["title", "brand", "asin", "seller"],
  filters: [
    {
      field: "site",
      type: "select",
      label: "Site",
      options: SITES.map((s) => ({ label: s, value: s })),
    },
    {
      field: "stock",
      type: "select",
      label: "Stock",
      options: [
        { label: "In stock", value: "in_stock" },
        { label: "Low stock", value: "low_stock" },
        { label: "Out of stock", value: "out_of_stock" },
      ],
    },
    { field: "priceCents", type: "numeric-range", label: "Price (cents)" },
  ],
  defaultSort: { field: "scrapedAt", dir: "desc" },
  // A dense, high-volume table reads better compact.
  density: "compact",
  create: { disabled: true },
  rowClick: "drawer",
  export: {
    formats: ["csv", "json"],
    fields: ["id", "asin", "site", "title", "brand", "category", "priceCents", "stock"],
  },
  drawer: {
    width: "lg",
    header: (row) => row.title,
    tabs: [
      {
        key: "detail",
        label: "Detail",
        fields: [
          "title",
          "site",
          "brand",
          "category",
          "priceCents",
          "currency",
          "seller",
          "stock",
          "rating",
          "reviews",
          "url",
          "scrapedAt",
        ],
      },
      {
        key: "match",
        label: "Match",
        resource: "matches",
        filter: (row) => ({ listingId: row.id }),
      },
    ],
  },
});
