import type { ModelMetadata, FieldMetadata } from "@flowpanel/core";
import { createTableRelationsHelpers } from "drizzle-orm";

/**
 * Duck-typed Drizzle column interface.
 * Drizzle columns expose these properties at runtime.
 */
interface DrizzleColumn {
  name: string;
  dataType: string; // "string" | "number" | "boolean" | "date" | "json" | "custom" | "bigint" | "array" | "buffer"
  columnType: string; // "PgVarchar" | "PgInteger" | "PgTimestamp" | "PgBoolean" | "PgJson" etc.
  notNull: boolean;
  hasDefault: boolean;
  primary: boolean;
  isAutoincrement?: boolean;
  enumValues?: string[];
}

function isDrizzleColumn(val: unknown): val is DrizzleColumn {
  if (!val || typeof val !== "object") return false;
  const v = val as Record<string, unknown>;
  return typeof v["dataType"] === "string" && typeof v["columnType"] === "string";
}

/**
 * Extract columns from a Drizzle table object using duck-typing.
 * Drizzle tables expose columns via table._.columns or as direct properties.
 */
function getColumnsFromTable(tableObj: unknown): Record<string, DrizzleColumn> {
  if (!tableObj || typeof tableObj !== "object") return {};

  const t = tableObj as Record<string, unknown>;

  // Try table._.columns first (internal Drizzle API)
  const underscore = t["_"];
  if (underscore && typeof underscore === "object") {
    const u = underscore as Record<string, unknown>;
    if (u["columns"] && typeof u["columns"] === "object") {
      const cols = u["columns"] as Record<string, unknown>;
      const result: Record<string, DrizzleColumn> = {};
      for (const [k, v] of Object.entries(cols)) {
        if (isDrizzleColumn(v)) result[k] = v;
      }
      if (Object.keys(result).length > 0) return result;
    }
  }

  // Fallback: scan direct properties for column objects
  const result: Record<string, DrizzleColumn> = {};
  for (const [k, v] of Object.entries(t)) {
    if (isDrizzleColumn(v)) result[k] = v;
  }
  return result;
}

/**
 * Derive the table name from the Drizzle table object.
 */
function getTableName(tableObj: unknown): string | undefined {
  if (!tableObj || typeof tableObj !== "object") return undefined;
  const t = tableObj as Record<string, unknown>;

  // table[Symbol.for("drizzle:Name")]
  const sym = Symbol.for("drizzle:Name");
  if ((t as unknown as Record<symbol, unknown>)[sym]) {
    return String((t as unknown as Record<symbol, unknown>)[sym]);
  }

  // table._.name
  const underscore = t["_"];
  if (underscore && typeof underscore === "object") {
    const u = underscore as Record<string, unknown>;
    if (typeof u["name"] === "string") return u["name"];
  }

  return undefined;
}

function mapDataType(col: DrizzleColumn): Pick<FieldMetadata, "type" | "kind" | "enumValues"> {
  // Enum columns
  if (col.enumValues && col.enumValues.length > 0) {
    return { type: "enum", kind: "enum", enumValues: col.enumValues };
  }

  switch (col.dataType) {
    case "string":
      return { type: "string", kind: "scalar", enumValues: undefined };
    case "number": {
      // Distinguish int vs float by columnType
      const colType = col.columnType.toLowerCase();
      if (
        colType.includes("float") ||
        colType.includes("real") ||
        colType.includes("double") ||
        colType.includes("numeric") ||
        colType.includes("decimal")
      ) {
        return { type: "float", kind: "scalar", enumValues: undefined };
      }
      return { type: "int", kind: "scalar", enumValues: undefined };
    }
    case "bigint":
      return { type: "int", kind: "scalar", enumValues: undefined };
    case "boolean":
      return { type: "boolean", kind: "scalar", enumValues: undefined };
    case "date":
      return { type: "datetime", kind: "scalar", enumValues: undefined };
    case "json":
      return { type: "json", kind: "scalar", enumValues: undefined };
    case "buffer":
    case "array":
    case "custom":
    default:
      return { type: "string", kind: "scalar", enumValues: undefined };
  }
}

function isAutoGenerated(col: DrizzleColumn): boolean {
  if (col.primary) return true;
  if (col.isAutoincrement) return true;
  if ((col.name === "createdAt" || col.name === "created_at") && col.hasDefault) return true;
  if ((col.name === "updatedAt" || col.name === "updated_at") && col.hasDefault) return true;
  return false;
}

/**
 * Extract ModelMetadata from a Drizzle table object.
 *
 * @param modelName  Logical model name (e.g. "User"). Caller supplies this.
 * @param tableObj   The Drizzle table object (e.g. schema.users).
 */
export function extractModelFromDrizzleTable(modelName: string, tableObj: unknown): ModelMetadata {
  const columns = getColumnsFromTable(tableObj);
  const tableName = getTableName(tableObj);

  const fields: FieldMetadata[] = Object.entries(columns).map(([propKey, col]) => {
    const typeInfo = mapDataType(col);
    return {
      name: propKey,
      isRequired: col.notNull && !col.hasDefault,
      isList: false,
      isId: col.primary,
      isAutoGenerated: isAutoGenerated(col),
      ...typeInfo,
    };
  });

  const pkField = fields.find((f) => f.isId);
  const primaryKey = pkField?.name ?? "id";

  return {
    name: modelName,
    ...(tableName !== undefined && tableName !== modelName ? { tableName } : {}),
    fields,
    primaryKey,
  };
}

/**
 * Duck-type check: is this value a Drizzle Relations object?
 * Relations objects have a `table` property (the table they belong to)
 * and a `config` function that returns the relation map.
 */
function isDrizzleRelations(v: unknown): boolean {
  if (!v || typeof v !== "object") return false;
  const obj = v as Record<string, unknown>;
  return typeof obj["config"] === "function" && "table" in obj;
}

/**
 * Build complete ModelMetadata from a full Drizzle schema (tables + relations exports).
 *
 * Unlike `extractModelFromDrizzleTable`, this function also scans for `relations(...)`
 * exports and adds `FieldMetadata` entries with `kind: "relation"` for each defined
 * relation, including the `relationModel` key name and `isList` flag.
 *
 * @param schema    The full schema object (e.g. `import * as schema from "./schema"`).
 * @param tableKey  The key of the table in the schema (e.g. "users").
 */
export function buildModelMetadata(
  schema: Record<string, unknown>,
  tableKey: string,
): ModelMetadata {
  const tableObj = schema[tableKey];
  if (!tableObj) {
    throw new Error(`[flowpanel] buildModelMetadata: table key "${tableKey}" not found in schema`);
  }

  // Start with scalar fields from the table
  const base = extractModelFromDrizzleTable(tableKey, tableObj);

  // Build a reverse map: table object identity → schema key
  // This lets us resolve relation targets back to their key names.
  const tablesByIdentity = new Map<unknown, string>();
  for (const [key, val] of Object.entries(schema)) {
    if (val && typeof val === "object" && !isDrizzleRelations(val)) {
      // Only add non-relations objects (i.e. actual table objects)
      tablesByIdentity.set(val, key);
    }
  }

  const relationFields: FieldMetadata[] = [];

  // Scan schema for Relations objects that belong to our table
  for (const val of Object.values(schema)) {
    if (!isDrizzleRelations(val)) continue;
    const relObj = val as Record<string, unknown>;

    // Only process relations for this table
    if (relObj["table"] !== tableObj) continue;

    // Call the config function with Drizzle's real helpers so One/Many instances
    // are constructed correctly (they require the sourceTable on their builders).
    let relMap: Record<string, unknown>;
    try {
      const helpers = createTableRelationsHelpers(tableObj);
      relMap = (relObj["config"] as (helpers: unknown) => Record<string, unknown>)(helpers);
    } catch {
      // If the config call fails (e.g. due to unexpected API differences), skip
      continue;
    }

    for (const [relName, def] of Object.entries(relMap)) {
      if (!def || typeof def !== "object") continue;
      const d = def as Record<string, unknown>;

      // Duck-type One vs Many: both have `referencedTable`.
      // Many has no `isNullable`; One has it. Simpler: check constructor name.
      const referencedTable = d["referencedTable"];
      if (!referencedTable) continue;

      const ctorName = (def as object).constructor?.name ?? "";
      const isList = ctorName === "Many";

      const targetKey = tablesByIdentity.get(referencedTable);
      if (!targetKey) continue;

      relationFields.push({
        name: relName,
        type: "relation",
        kind: "relation",
        isRequired: false,
        isList,
        isId: false,
        isAutoGenerated: false,
        relationModel: targetKey,
      });
    }
  }

  return {
    ...base,
    fields: [...base.fields, ...relationFields],
  };
}
