import type { ModelMetadata, FieldMetadata } from "@flowpanel/core";

/**
 * Duck-typed Drizzle column interface.
 * Drizzle columns expose these properties at runtime.
 */
interface DrizzleColumn {
  name: string;
  dataType: string; // "string" | "number" | "boolean" | "date" | "json" | "custom" | "bigint" | "array" | "buffer"
  columnType: string; // "PgVarchar" | "PgInteger" | "PgTimestamp" | "PgBoolean" | "PgJson" etc.
  notNull: boolean;
  hasDefault: boolean;
  primary: boolean;
  isAutoincrement?: boolean;
  enumValues?: string[];
}

function isDrizzleColumn(val: unknown): val is DrizzleColumn {
  if (!val || typeof val !== "object") return false;
  const v = val as Record<string, unknown>;
  return typeof v["dataType"] === "string" && typeof v["columnType"] === "string";
}

/**
 * Extract columns from a Drizzle table object using duck-typing.
 * Drizzle tables expose columns via table._.columns or as direct properties.
 */
function getColumnsFromTable(tableObj: unknown): Record<string, DrizzleColumn> {
  if (!tableObj || typeof tableObj !== "object") return {};

  const t = tableObj as Record<string, unknown>;

  // Try table._.columns first (internal Drizzle API)
  const underscore = t["_"];
  if (underscore && typeof underscore === "object") {
    const u = underscore as Record<string, unknown>;
    if (u["columns"] && typeof u["columns"] === "object") {
      const cols = u["columns"] as Record<string, unknown>;
      const result: Record<string, DrizzleColumn> = {};
      for (const [k, v] of Object.entries(cols)) {
        if (isDrizzleColumn(v)) result[k] = v;
      }
      if (Object.keys(result).length > 0) return result;
    }
  }

  // Fallback: scan direct properties for column objects
  const result: Record<string, DrizzleColumn> = {};
  for (const [k, v] of Object.entries(t)) {
    if (isDrizzleColumn(v)) result[k] = v;
  }
  return result;
}

/**
 * Derive the table name from the Drizzle table object.
 */
function getTableName(tableObj: unknown): string | undefined {
  if (!tableObj || typeof tableObj !== "object") return undefined;
  const t = tableObj as Record<string, unknown>;

  // table[Symbol.for("drizzle:Name")]
  const sym = Symbol.for("drizzle:Name");
  if ((t as unknown as Record<symbol, unknown>)[sym]) {
    return String((t as unknown as Record<symbol, unknown>)[sym]);
  }

  // table._.name
  const underscore = t["_"];
  if (underscore && typeof underscore === "object") {
    const u = underscore as Record<string, unknown>;
    if (typeof u["name"] === "string") return u["name"];
  }

  return undefined;
}

function mapDataType(col: DrizzleColumn): Pick<FieldMetadata, "type" | "kind" | "enumValues"> {
  // Enum columns
  if (col.enumValues && col.enumValues.length > 0) {
    return { type: "enum", kind: "enum", enumValues: col.enumValues };
  }

  switch (col.dataType) {
    case "string":
      return { type: "string", kind: "scalar", enumValues: undefined };
    case "number": {
      // Distinguish int vs float by columnType
      const colType = col.columnType.toLowerCase();
      if (
        colType.includes("float") ||
        colType.includes("real") ||
        colType.includes("double") ||
        colType.includes("numeric") ||
        colType.includes("decimal")
      ) {
        return { type: "float", kind: "scalar", enumValues: undefined };
      }
      return { type: "int", kind: "scalar", enumValues: undefined };
    }
    case "bigint":
      return { type: "int", kind: "scalar", enumValues: undefined };
    case "boolean":
      return { type: "boolean", kind: "scalar", enumValues: undefined };
    case "date":
      return { type: "datetime", kind: "scalar", enumValues: undefined };
    case "json":
      return { type: "json", kind: "scalar", enumValues: undefined };
    case "buffer":
    case "array":
    case "custom":
    default:
      return { type: "string", kind: "scalar", enumValues: undefined };
  }
}

function isAutoGenerated(col: DrizzleColumn): boolean {
  if (col.primary) return true;
  if (col.isAutoincrement) return true;
  if ((col.name === "createdAt" || col.name === "created_at") && col.hasDefault) return true;
  if ((col.name === "updatedAt" || col.name === "updated_at") && col.hasDefault) return true;
  return false;
}

/**
 * Extract ModelMetadata from a Drizzle table object.
 *
 * @param modelName  Logical model name (e.g. "User"). Caller supplies this.
 * @param tableObj   The Drizzle table object (e.g. schema.users).
 */
export function extractModelFromDrizzleTable(modelName: string, tableObj: unknown): ModelMetadata {
  const columns = getColumnsFromTable(tableObj);
  const tableName = getTableName(tableObj);

  const fields: FieldMetadata[] = Object.entries(columns).map(([propKey, col]) => {
    const typeInfo = mapDataType(col);
    return {
      name: propKey,
      isRequired: col.notNull && !col.hasDefault,
      isList: false,
      isId: col.primary,
      isAutoGenerated: isAutoGenerated(col),
      ...typeInfo,
    };
  });

  const pkField = fields.find((f) => f.isId);
  const primaryKey = pkField?.name ?? "id";

  return {
    name: modelName,
    ...(tableName !== undefined && tableName !== modelName ? { tableName } : {}),
    fields,
    primaryKey,
  };
}
