// `flowpanel` is the umbrella package. It re-exports the typed config DSL,
// runtime helpers, and types from @flowpanel/core. Adapters, the Next.js
// bridge, the React UI, and chart builders live behind subpaths:
//   - flowpanel/drizzle, flowpanel/prisma   — adapter helpers
//   - flowpanel/next                         — Flowpanel(config), handlers(), stream()
//   - flowpanel/charts                       — areaChart / barChart / lineChart / pieChart
//   - flowpanel/client                       — client-side hooks (useLiveChannel, etc.)
//   - flowpanel/auth                         — withClerk / withNextAuth / withLucia presets
// See `package.json#exports` for the full subpath surface.

// ── Types — config ──────────────────────────────────────────────────────────
// ── Types — DSL ────────────────────────────────────────────────────────────
// ── Types — dashboard + widgets ────────────────────────────────────────────
// ── Types — drawer ─────────────────────────────────────────────────────────
// ── Types — adapter + runtime contexts ────────────────────────────────────
// ── Types — registry + queue + realtime + labels + palette + session ──────
export type {
  ActionContext,
  ActionResult,
  Adapter,
  AdminConfig,
  AreaChartOptions,
  AreaChartWidget,
  AuditConfig,
  AuditEvent,
  AuthConfig,
  BarChartOptions,
  BarChartWidget,
  BulkAction,
  ChartBucket,
  ChartOptionsBase,
  ColumnDef,
  ColumnMeta,
  CommandGroup,
  CommandItem,
  CommandPaletteConfig,
  CustomOptions,
  CustomWidget,
  DashboardAction,
  DashboardConfig,
  DateRangeConfig,
  DateRangePreset,
  DetailTab,
  DrawerAction,
  DrawerConfig,
  DrawerFieldFormSpec,
  DrawerTab,
  DrawerTabFields,
  DrawerTabResource,
  DrawerTabWidgets,
  DrawerWidth,
  FieldDef,
  FieldType,
  FilterDef,
  FilterType,
  FlowpanelComponentSlots,
  FlowpanelTypes,
  InferDB,
  InferRow,
  ItemQueryContext,
  LabelsConfig,
  LineChartOptions,
  LineChartWidget,
  ListQueryContext,
  ListResult,
  MetricDelta,
  MetricOptions,
  MetricWidget,
  MutationContext,
  NumericFormat,
  PageConfig,
  PieChartOptions,
  PieChartWidget,
  Publisher,
  PublisherOptions,
  QueryContext,
  QueueConfig,
  QueueOptions,
  RateLimitConfig,
  RateLimiter,
  RateLimitOptions,
  RealtimeConfig,
  RequestContext,
  RequireRole,
  ResolvedAdminConfig,
  ResolvedDateRange,
  ResolvedLabels,
  ResourceConfig,
  ResourceIntrospection,
  ResourceOptions,
  RowAction,
  Scope,
  ScopeCheckInput,
  ScopeContext,
  SectionConfig,
  SelectOption,
  Session,
  ShellConfig,
  ShellMode,
  Span,
  StatGroupOptions,
  StatGroupWidget,
  StatItem,
  TableWidget,
  TableWidgetOptions,
  ThemeConfig,
  Tone,
  WidgetConfig,
  WidgetContext,
} from "@flowpanel/core";
// ── Builders ────────────────────────────────────────────────────────────────
// ── Runtime helpers ─────────────────────────────────────────────────────────
// ── Errors ──────────────────────────────────────────────────────────────────
// ── Labels (i18n) ───────────────────────────────────────────────────────────
export {
  assertResourceScope,
  checkRequireRole,
  createPublisher,
  createRateLimiter,
  custom,
  DEFAULT_LABELS,
  dashboard,
  defineAdmin,
  emitAudit,
  FlowpanelAccessError,
  FlowpanelAuthError,
  FlowpanelConflictError,
  FlowpanelError,
  FlowpanelNotFoundError,
  FlowpanelRateLimitError,
  FlowpanelValidationError,
  formatLabel,
  getRequestContext,
  mergeLabels,
  metric,
  page,
  queue,
  resource,
  runWithRequestContext,
  statGroup,
  table,
  tryGetRequestContext,
} from "@flowpanel/core";
