/**
 * Request-scoped helpers for the resource tRPC procedures.
 *
 * Every procedure needs the same: look up a resource, check access,
 * coerce filter input, strip non-writable fields. Keeping them here
 * lets each procedure read as a straight narrative of "load → check →
 * act → serialize" without helper scaffolding mixed in.
 */

import { TRPCError } from "@trpc/server";
import type {
  AccessRule,
  ModelMetadata,
  NormalizedFilter,
  ResolvedResource,
  ResourceAdapter,
  Row,
} from "../../../resource/types";
import { publishResourceEvent, type ResourceEventPayload } from "../../../sse/publisher";
import type { Session } from "../../../types/config";
import type { FlowPanelContext } from "../../context";

// ─── Access ────────────────────────────────────────────────────────────

export function checkAccess(
  rule: AccessRule | undefined,
  sessionRoles: string[],
  ctx?: { session: Session | null },
  row?: Row,
): boolean {
  if (rule === false) return false;
  if (rule === undefined) return true;
  if (Array.isArray(rule)) return rule.some((r) => sessionRoles.includes(r));
  if (typeof rule === "function") return rule(ctx, row);
  return true;
}

export function getSessionRoles(session: Session | null): string[] {
  if (!session) return [];
  return session.role ? [session.role] : [];
}

// ─── Lookup ────────────────────────────────────────────────────────────

export function getResource(ctx: FlowPanelContext, resourceId: string): ResolvedResource {
  if (!ctx.resources) {
    throw new TRPCError({
      code: "NOT_FOUND",
      message: "No resources configured.",
    });
  }
  const resource = ctx.resources[resourceId];
  if (!resource) {
    throw new TRPCError({
      code: "NOT_FOUND",
      message: `Resource "${resourceId}" not found.`,
    });
  }
  return resource;
}

export function getAdapter(ctx: FlowPanelContext): ResourceAdapter {
  if (!ctx.resourceAdapter) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "No resource adapter configured.",
    });
  }
  return ctx.resourceAdapter;
}

// ─── Transforms ───────────────────────────────────────────────────────

export function applyComputes(resource: ResolvedResource, row: Row): Row {
  const result = { ...row };
  for (const [id, compute] of Object.entries(resource._computes)) {
    result[id] = compute(row);
  }
  return result;
}

/**
 * Strips non-writable fields (auto-generated, primary key, unknown) from
 * user-submitted data before passing to the adapter.
 */
export function filterWritableData(
  data: Record<string, unknown>,
  metadata: ModelMetadata,
): Record<string, unknown> {
  const filtered: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(data)) {
    const field = metadata.fields.find((f) => f.name === key);
    if (!field) continue; // skip unknown fields
    if (field.isAutoGenerated) continue; // skip auto-generated (id, createdAt, etc.)
    if (field.isId) continue; // skip primary key
    filtered[key] = value;
  }
  return filtered;
}

// ─── Filters ──────────────────────────────────────────────────────────

export function buildFilters(
  inputFilters: NormalizedFilter[] | undefined,
  search: { query: string; fields?: string[] } | undefined,
  resource: ResolvedResource,
): { where: NormalizedFilter[]; searchOr: NormalizedFilter[] } {
  const where: NormalizedFilter[] = [];
  const searchOr: NormalizedFilter[] = [];

  // Regular filters (AND semantics)
  if (inputFilters) {
    where.push(...inputFilters);
  }

  // Search → contains filters on search fields (OR semantics)
  if (search?.query && search.query.length > 0) {
    const searchFields =
      search.fields && search.fields.length > 0 ? search.fields : resource.searchFields;
    for (const field of searchFields) {
      searchOr.push({ field, op: "contains", value: search.query });
    }
  }

  return { where, searchOr };
}

// ─── Row-level security ───────────────────────────────────────────────

/**
 * Check a single row against rowLevel scalar filters. Returns false if any
 * enforced field on the row doesn't match. Used for get/update/delete/action
 * to refuse access to rows outside the session's scope.
 */
export function rowPassesRowLevel(row: Row, rowLevel: NormalizedFilter[]): boolean {
  for (const f of rowLevel) {
    const actual = row[f.field];
    if (f.op === "eq") {
      if (actual !== f.value) return false;
    } else if (f.op === "in") {
      if (!Array.isArray(f.value) || !f.value.includes(actual)) return false;
    } else if (f.op === "isNull") {
      if (actual !== null && actual !== undefined) return false;
    }
  }
  return true;
}

/**
 * Invoke the global rowLevel filter (config.security.rowLevel?.filter) for the
 * current session and convert returned scalar fields into NormalizedFilter[].
 *
 * The filter function is passed `(session, { resource: resourceId })` so users
 * can dispatch per-resource. Return shape: `Record<string, unknown>` where each
 * key is a field path and value is the enforced scalar (eq filter).
 *
 * Nested objects/arrays in returned values are ignored here — users with complex
 * needs should use `access` rules with row predicates.
 */
// ─── Realtime ─────────────────────────────────────────────────────────

/**
 * Publish a realtime event if the resource opted in via `realtime: true`.
 * The `_realtime` flag is set by `lowerTypedResource`; old-style resources
 * default to false. Fire-and-forget — errors already swallowed by publisher.
 */
export async function maybePublish(
  ctx: FlowPanelContext,
  resource: ResolvedResource,
  resourceKey: string,
  payload: ResourceEventPayload,
): Promise<void> {
  const realtime = (resource as ResolvedResource & { _realtime?: boolean })._realtime;
  if (!realtime) return;
  await publishResourceEvent(ctx.db, resourceKey, payload);
}

export function getRowLevelFilters(
  ctx: FlowPanelContext & { session: Session },
  resourceId: string,
): NormalizedFilter[] {
  const filterFn = ctx.config?.security?.rowLevel?.filter as
    | ((session: Session, fctx: Record<string, unknown>) => Record<string, unknown> | undefined)
    | undefined;
  if (!filterFn) return [];
  const result = filterFn(ctx.session, { resource: resourceId });
  if (!result || typeof result !== "object") return [];

  const filters: NormalizedFilter[] = [];
  for (const [field, value] of Object.entries(result)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      filters.push({ field, op: "in", value });
    } else if (value === null) {
      filters.push({ field, op: "isNull", value: null });
    } else if (typeof value === "object") {
      // Nested shapes aren't expressible as NormalizedFilter — skip and let the
      // user write an `access` row predicate for the complex cases.
    } else {
      filters.push({ field, op: "eq", value });
    }
  }
  return filters;
}
