import type { ModelMetadata, FieldMetadata } from "@flowpanel/core";

// Prisma DMMF types (from @prisma/client runtime)
export interface DmmfField {
  name: string;
  kind: "scalar" | "object" | "enum" | "unsupported";
  type: string; // "String", "Int", "DateTime", "Boolean", "Json", "User", "Role"
  isRequired: boolean;
  isList: boolean;
  isId: boolean;
  isReadOnly: boolean;
  isGenerated?: boolean;
  isUpdatedAt?: boolean;
  hasDefaultValue: boolean;
  default?: unknown;
  relationName?: string;
  relationFromFields?: string[];
}

export interface DmmfModel {
  name: string;
  dbName: string | null;
  fields: DmmfField[];
}

export interface DmmfEnum {
  name: string;
  values: { name: string }[];
}

export interface DmmfDatamodel {
  models: DmmfModel[];
  enums: DmmfEnum[];
}

function mapFieldType(
  field: DmmfField,
  enumValues: Map<string, string[]>,
): Pick<FieldMetadata, "type" | "kind" | "enumValues" | "relationModel"> {
  if (field.kind === "enum") {
    return {
      type: "enum",
      kind: "enum",
      enumValues: enumValues.get(field.type) ?? [],
    };
  }

  if (field.kind === "object") {
    return {
      type: "relation",
      kind: "relation",
      relationModel: field.type,
    };
  }

  // scalar
  switch (field.type) {
    case "String":
      return { type: "string", kind: "scalar" };
    case "Int":
    case "BigInt":
      return { type: "int", kind: "scalar" };
    case "Float":
    case "Decimal":
      return { type: "float", kind: "scalar" };
    case "Boolean":
      return { type: "boolean", kind: "scalar" };
    case "DateTime":
      return { type: "datetime", kind: "scalar" };
    case "Json":
      return { type: "json", kind: "scalar" };
    default:
      return { type: "string", kind: "scalar" };
  }
}

function isAutoGenerated(field: DmmfField): boolean {
  return (
    field.isId ||
    field.isUpdatedAt === true ||
    (field.name === "createdAt" && field.hasDefaultValue)
  );
}

export function extractEnumsFromDmmf(dmmf: { datamodel: DmmfDatamodel }): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const e of dmmf.datamodel.enums) {
    map.set(
      e.name,
      e.values.map((v) => v.name),
    );
  }
  return map;
}

export function extractModelsFromDmmf(dmmf: {
  datamodel: DmmfDatamodel;
}): Map<string, ModelMetadata> {
  const enumMap = extractEnumsFromDmmf(dmmf);
  const map = new Map<string, ModelMetadata>();

  for (const model of dmmf.datamodel.models) {
    const fields: FieldMetadata[] = model.fields.map((f) => {
      const typeInfo = mapFieldType(f, enumMap);
      return {
        name: f.name,
        isRequired: f.isRequired,
        isList: f.isList,
        isId: f.isId,
        isAutoGenerated: isAutoGenerated(f),
        default: f.default,
        ...typeInfo,
      };
    });

    const idField = model.fields.find((f) => f.isId);
    const primaryKey = idField?.name ?? "id";

    map.set(model.name, {
      name: model.name,
      tableName: model.dbName ?? undefined,
      fields,
      primaryKey,
    });
  }

  return map;
}
