import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { serializeResource } from "../../resource/serializer";
import type {
  AccessRule,
  ModelMetadata,
  NormalizedFilter,
  ResolvedResource,
  ResourceAdapter,
  Row,
} from "../../resource/types";
import type { Session } from "../../types/config";
import type { FlowPanelContext } from "../context";

// ---------------------------------------------------------------------------
// Input schemas
// ---------------------------------------------------------------------------

const filterInputSchema = z.object({
  field: z.string(),
  op: z.enum([
    "eq",
    "neq",
    "contains",
    "startsWith",
    "endsWith",
    "in",
    "notIn",
    "gte",
    "lte",
    "gt",
    "lt",
    "isNull",
    "isNotNull",
  ]),
  value: z.unknown(),
});

const listInputSchema = z.object({
  resourceId: z.string(),
  page: z.number().int().min(1).default(1),
  pageSize: z.number().int().min(1).max(200).default(50),
  sort: z
    .object({
      field: z.string(),
      dir: z.enum(["asc", "desc"]),
    })
    .optional(),
  search: z
    .object({
      query: z.string(),
      fields: z.array(z.string()).optional(),
    })
    .optional(),
  filters: z.array(filterInputSchema).optional(),
});

const getInputSchema = z.object({
  resourceId: z.string(),
  recordId: z.union([z.string(), z.number()]),
});

const createInputSchema = z.object({
  resourceId: z.string(),
  data: z.record(z.unknown()),
});

const updateInputSchema = z.object({
  resourceId: z.string(),
  recordId: z.union([z.string(), z.number()]),
  data: z.record(z.unknown()),
});

const deleteInputSchema = z.object({
  resourceId: z.string(),
  recordId: z.union([z.string(), z.number()]),
});

const actionInputSchema = z.object({
  resourceId: z.string(),
  actionId: z.string(),
  recordId: z.union([z.string(), z.number()]),
});

const bulkActionInputSchema = z.object({
  resourceId: z.string(),
  actionId: z.string(),
  recordIds: z
    .array(z.union([z.string(), z.number()]))
    .min(1)
    .max(1000),
});

const collectionActionInputSchema = z.object({
  resourceId: z.string(),
  actionId: z.string(),
});

const dialogActionInputSchema = z.object({
  resourceId: z.string(),
  actionId: z.string(),
  values: z.record(z.unknown()),
  recordId: z.union([z.string(), z.number()]).optional(),
});

// ---------------------------------------------------------------------------
// Access helpers
// ---------------------------------------------------------------------------

function checkAccess(
  rule: AccessRule | undefined,
  sessionRoles: string[],
  ctx?: { session: Session | null },
  row?: Row,
): boolean {
  if (rule === false) return false;
  if (rule === undefined) return true;
  if (Array.isArray(rule)) return rule.some((r) => sessionRoles.includes(r));
  if (typeof rule === "function") return rule(ctx, row);
  return true;
}

function getSessionRoles(session: Session | null): string[] {
  if (!session) return [];
  return session.role ? [session.role] : [];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getResource(ctx: FlowPanelContext, resourceId: string): ResolvedResource {
  if (!ctx.resources) {
    throw new TRPCError({
      code: "NOT_FOUND",
      message: "No resources configured.",
    });
  }
  const resource = ctx.resources[resourceId];
  if (!resource) {
    throw new TRPCError({
      code: "NOT_FOUND",
      message: `Resource "${resourceId}" not found.`,
    });
  }
  return resource;
}

function getAdapter(ctx: FlowPanelContext): ResourceAdapter {
  if (!ctx.resourceAdapter) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "No resource adapter configured.",
    });
  }
  return ctx.resourceAdapter;
}

function applyComputes(resource: ResolvedResource, row: Row): Row {
  const result = { ...row };
  for (const [id, compute] of Object.entries(resource._computes)) {
    result[id] = compute(row);
  }
  return result;
}

/**
 * Strips non-writable fields (auto-generated, primary key, unknown) from
 * user-submitted data before passing to the adapter.
 */
function filterWritableData(
  data: Record<string, unknown>,
  metadata: ModelMetadata,
): Record<string, unknown> {
  const filtered: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(data)) {
    const field = metadata.fields.find((f) => f.name === key);
    if (!field) continue; // skip unknown fields
    if (field.isAutoGenerated) continue; // skip auto-generated (id, createdAt, etc.)
    if (field.isId) continue; // skip primary key
    filtered[key] = value;
  }
  return filtered;
}

function buildFilters(
  inputFilters: NormalizedFilter[] | undefined,
  search: { query: string; fields?: string[] } | undefined,
  resource: ResolvedResource,
): { where: NormalizedFilter[]; searchOr: NormalizedFilter[] } {
  const where: NormalizedFilter[] = [];
  const searchOr: NormalizedFilter[] = [];

  // Regular filters (AND semantics)
  if (inputFilters) {
    where.push(...inputFilters);
  }

  // Search → contains filters on search fields (OR semantics)
  if (search?.query && search.query.length > 0) {
    const searchFields =
      search.fields && search.fields.length > 0 ? search.fields : resource.searchFields;
    for (const field of searchFields) {
      searchOr.push({ field, op: "contains", value: search.query });
    }
  }

  return { where, searchOr };
}

/**
 * Check a single row against rowLevel scalar filters. Returns false if any
 * enforced field on the row doesn't match. Used for get/update/delete/action
 * to refuse access to rows outside the session's scope.
 */
function rowPassesRowLevel(row: Row, rowLevel: NormalizedFilter[]): boolean {
  for (const f of rowLevel) {
    const actual = row[f.field];
    if (f.op === "eq") {
      if (actual !== f.value) return false;
    } else if (f.op === "in") {
      if (!Array.isArray(f.value) || !f.value.includes(actual)) return false;
    } else if (f.op === "isNull") {
      if (actual !== null && actual !== undefined) return false;
    }
  }
  return true;
}

/**
 * Invoke the global rowLevel filter (config.security.rowLevel?.filter) for the
 * current session and convert returned scalar fields into NormalizedFilter[].
 *
 * The filter function is passed `(session, { resource: resourceId })` so users
 * can dispatch per-resource. Return shape: `Record<string, unknown>` where each
 * key is a field path and value is the enforced scalar (eq filter).
 *
 * Nested objects/arrays in returned values are ignored here — users with complex
 * needs should use `access` rules with row predicates.
 */
function getRowLevelFilters(
  ctx: FlowPanelContext & { session: Session },
  resourceId: string,
): NormalizedFilter[] {
  const filterFn = ctx.config?.security?.rowLevel?.filter as
    | ((session: Session, fctx: Record<string, unknown>) => Record<string, unknown> | undefined)
    | undefined;
  if (!filterFn) return [];
  const result = filterFn(ctx.session, { resource: resourceId });
  if (!result || typeof result !== "object") return [];

  const filters: NormalizedFilter[] = [];
  for (const [field, value] of Object.entries(result)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      filters.push({ field, op: "in", value });
    } else if (value === null) {
      filters.push({ field, op: "isNull", value: null });
    } else if (typeof value === "object") {
      // Skip nested objects — not supported in rowLevel scalar shape
      continue;
    } else {
      filters.push({ field, op: "eq", value });
    }
  }
  return filters;
}

// ---------------------------------------------------------------------------
// Procedure creator
// ---------------------------------------------------------------------------

export function createResourceProcedures(
  // biome-ignore lint/suspicious/noExplicitAny: tRPC internal builder type
  t: { procedure: any; router: (routes: any) => any },
  // biome-ignore lint/suspicious/noExplicitAny: tRPC internal builder type
  authedProcedure: any,
) {
  return t.router({
    // ---- list ---------------------------------------------------------------
    list: authedProcedure
      .input(listInputSchema)
      .query(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof listInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          // Check list access
          if (!checkAccess(resource.access.list, roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: "Not allowed to list this resource.",
            });
          }

          const { where, searchOr } = buildFilters(
            input.filters as NormalizedFilter[] | undefined,
            input.search,
            resource,
          );
          // Inject row-level security filters
          where.push(...getRowLevelFilters(ctx, input.resourceId));
          const sort = input.sort ?? resource.defaultSort;
          const pageSize = input.pageSize ?? resource.defaultPageSize;
          const skip = (input.page - 1) * pageSize;

          const { data, total } = await adapter.findMany(resource.modelName, {
            where: where.length > 0 ? where : undefined,
            searchOr: searchOr.length > 0 ? searchOr : undefined,
            orderBy: sort,
            skip,
            take: pageSize,
            include: resource.include,
          });

          // Apply computed columns
          const rows = data.map((row) => applyComputes(resource, row));

          return {
            data: rows,
            total,
            page: input.page,
            pageSize,
            totalPages: Math.ceil(total / pageSize),
          };
        },
      ),

    // ---- get ----------------------------------------------------------------
    get: authedProcedure
      .input(getInputSchema)
      .query(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof getInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          if (!checkAccess(resource.access.read, roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: "Not allowed to read this resource.",
            });
          }

          const metadata = adapter.getModelMetadata(resource.modelName);
          const pk = metadata.primaryKey;

          const row = await adapter.findUnique(resource.modelName, {
            where: { [pk]: input.recordId },
            include: resource.include,
          });

          if (!row) {
            throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
          }

          // Enforce row-level security
          const rowLevel = getRowLevelFilters(ctx, input.resourceId);
          if (rowLevel.length > 0 && !rowPassesRowLevel(row, rowLevel)) {
            throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
          }

          return applyComputes(resource, row);
        },
      ),

    // ---- create -------------------------------------------------------------
    create: authedProcedure
      .input(createInputSchema)
      .mutation(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof createInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          if (!checkAccess(resource.access.create, roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: "Not allowed to create this resource.",
            });
          }

          const metadata = adapter.getModelMetadata(resource.modelName);
          const safeData = filterWritableData(input.data, metadata);

          // Enforce row-level security on create: force-apply the scalar fields
          // returned by the rowLevel filter so a user can't escape their scope.
          const rowLevel = getRowLevelFilters(ctx, input.resourceId);
          for (const f of rowLevel) {
            if (f.op === "eq") {
              safeData[f.field] = f.value;
            }
          }

          const row = await adapter.create(resource.modelName, { data: safeData });
          return applyComputes(resource, row);
        },
      ),

    // ---- update -------------------------------------------------------------
    update: authedProcedure
      .input(updateInputSchema)
      .mutation(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof updateInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          if (!checkAccess(resource.access.update, roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: "Not allowed to update this resource.",
            });
          }

          const metadata = adapter.getModelMetadata(resource.modelName);
          const pk = metadata.primaryKey;

          // Enforce row-level security: fetch and check before mutating
          const rowLevel = getRowLevelFilters(ctx, input.resourceId);
          if (rowLevel.length > 0) {
            const existing = await adapter.findUnique(resource.modelName, {
              where: { [pk]: input.recordId },
            });
            if (!existing || !rowPassesRowLevel(existing, rowLevel)) {
              throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
            }
          }

          const safeData = filterWritableData(input.data, metadata);
          const row = await adapter.update(resource.modelName, {
            where: { [pk]: input.recordId },
            data: safeData,
          });
          return applyComputes(resource, row);
        },
      ),

    // ---- delete -------------------------------------------------------------
    delete: authedProcedure
      .input(deleteInputSchema)
      .mutation(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof deleteInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          if (!checkAccess(resource.access.delete, roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: "Not allowed to delete this resource.",
            });
          }

          const metadata = adapter.getModelMetadata(resource.modelName);
          const pk = metadata.primaryKey;

          // Enforce row-level security: fetch and check before deleting
          const rowLevel = getRowLevelFilters(ctx, input.resourceId);
          if (rowLevel.length > 0) {
            const existing = await adapter.findUnique(resource.modelName, {
              where: { [pk]: input.recordId },
            });
            if (!existing || !rowPassesRowLevel(existing, rowLevel)) {
              throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
            }
          }

          await adapter.delete(resource.modelName, {
            where: { [pk]: input.recordId },
          });

          return { success: true as const };
        },
      ),

    // ---- action -------------------------------------------------------------
    action: authedProcedure
      .input(actionInputSchema)
      .mutation(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof actionInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          // Check per-action access
          if (!checkAccess(resource.access[input.actionId], roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: `Not allowed to perform action "${input.actionId}".`,
            });
          }

          const action = resource.actions.find((a) => a.id === input.actionId);
          if (!action) {
            throw new TRPCError({
              code: "NOT_FOUND",
              message: `Action "${input.actionId}" not found on resource "${input.resourceId}".`,
            });
          }
          if (action.type !== "mutation") {
            throw new TRPCError({
              code: "BAD_REQUEST",
              message: `Action "${input.actionId}" is not a per-row mutation. Use action.${action.type} procedure instead.`,
            });
          }
          const handler = resource._handlers[input.actionId];
          if (!handler) {
            throw new TRPCError({
              code: "NOT_FOUND",
              message: `Action "${input.actionId}" handler missing.`,
            });
          }

          // Fetch the row
          const metadata = adapter.getModelMetadata(resource.modelName);
          const pk = metadata.primaryKey;
          const row = await adapter.findUnique(resource.modelName, {
            where: { [pk]: input.recordId },
            include: resource.include,
          });

          if (!row) {
            throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
          }

          // Enforce row-level security
          const rowLevel = getRowLevelFilters(ctx, input.resourceId);
          if (rowLevel.length > 0 && !rowPassesRowLevel(row, rowLevel)) {
            throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
          }

          // Check `when` predicate
          const whenPredicate = resource._whens[input.actionId];
          if (whenPredicate && !whenPredicate(row)) {
            throw new TRPCError({
              code: "BAD_REQUEST",
              message: `Action "${input.actionId}" is not available for this record.`,
            });
          }

          const result = await handler(row, ctx);
          return result ?? { success: true };
        },
      ),

    // ---- actionBulk ---------------------------------------------------------
    actionBulk: authedProcedure
      .input(bulkActionInputSchema)
      .mutation(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof bulkActionInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          if (!checkAccess(resource.access[input.actionId], roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: `Not allowed to perform action "${input.actionId}".`,
            });
          }

          const action = resource.actions.find((a) => a.id === input.actionId);
          if (!action || action.type !== "bulk") {
            throw new TRPCError({
              code: "BAD_REQUEST",
              message: `Action "${input.actionId}" is not a bulk action.`,
            });
          }

          const metadata = adapter.getModelMetadata(resource.modelName);
          const pk = metadata.primaryKey;
          const rowLevel = getRowLevelFilters(ctx, input.resourceId);

          // Fetch all rows in a single query
          const rowsResult = await adapter.findMany(resource.modelName, {
            where: [{ field: pk, op: "in", value: input.recordIds }, ...rowLevel],
            include: resource.include,
            take: input.recordIds.length,
          });

          const handler = action.handler as (rows: Row[], ctx: unknown) => Promise<unknown>;
          const result = await handler(rowsResult.data, ctx);
          return result ?? { success: true, affected: rowsResult.data.length };
        },
      ),

    // ---- actionCollection ---------------------------------------------------
    actionCollection: authedProcedure
      .input(collectionActionInputSchema)
      .mutation(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof collectionActionInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const roles = getSessionRoles(ctx.session);

          if (!checkAccess(resource.access[input.actionId], roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: `Not allowed to perform action "${input.actionId}".`,
            });
          }

          const action = resource.actions.find((a) => a.id === input.actionId);
          if (!action || action.type !== "collection") {
            throw new TRPCError({
              code: "BAD_REQUEST",
              message: `Action "${input.actionId}" is not a collection action.`,
            });
          }

          const handler = action.handler as (ctx: unknown) => Promise<unknown>;
          const result = await handler(ctx);
          return result ?? { success: true };
        },
      ),

    // ---- actionDialog -------------------------------------------------------
    actionDialog: authedProcedure
      .input(dialogActionInputSchema)
      .mutation(
        async ({
          ctx,
          input,
        }: {
          ctx: FlowPanelContext & { session: Session };
          input: z.infer<typeof dialogActionInputSchema>;
        }) => {
          const resource = getResource(ctx, input.resourceId);
          const adapter = getAdapter(ctx);
          const roles = getSessionRoles(ctx.session);

          if (!checkAccess(resource.access[input.actionId], roles, ctx)) {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: `Not allowed to perform action "${input.actionId}".`,
            });
          }

          const action = resource.actions.find((a) => a.id === input.actionId);
          if (!action || action.type !== "dialog") {
            throw new TRPCError({
              code: "BAD_REQUEST",
              message: `Action "${input.actionId}" is not a dialog action.`,
            });
          }

          // Validate fields against schema
          for (const field of action.schema.fields) {
            if (field.required && input.values[field.name] == null) {
              throw new TRPCError({
                code: "BAD_REQUEST",
                message: `Field "${field.name}" is required.`,
              });
            }
          }

          let row: Row | null = null;
          if (input.recordId !== undefined) {
            const metadata = adapter.getModelMetadata(resource.modelName);
            const pk = metadata.primaryKey;
            row = await adapter.findUnique(resource.modelName, {
              where: { [pk]: input.recordId },
              include: resource.include,
            });
            if (!row) {
              throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
            }
            const rowLevel = getRowLevelFilters(ctx, input.resourceId);
            if (rowLevel.length > 0 && !rowPassesRowLevel(row, rowLevel)) {
              throw new TRPCError({ code: "NOT_FOUND", message: "Record not found." });
            }
          }

          const handler = action.handler as (
            values: Record<string, unknown>,
            row: Row | null,
            ctx: unknown,
          ) => Promise<unknown>;
          const result = await handler(input.values, row, ctx);
          return result ?? { success: true };
        },
      ),

    // ---- schema -------------------------------------------------------------
    schema: authedProcedure
      .input(z.object({}).optional())
      .query(async ({ ctx }: { ctx: FlowPanelContext & { session: Session } }) => {
        if (!ctx.resources) {
          return { resources: {} };
        }

        const roles = getSessionRoles(ctx.session);
        const serialized: Record<string, ReturnType<typeof serializeResource>> = {};

        for (const [key, resource] of Object.entries(ctx.resources)) {
          serialized[key] = serializeResource(resource, roles);
        }

        return { resources: serialized };
      }),
  });
}
