import type { IconName } from "@flowpanel/core";
import {
  Activity,
  Archive,
  BadgeDollarSign,
  Ban,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Boxes,
  BriefcaseBusiness,
  Calendar,
  Check,
  CircleDollarSign,
  CircleHelp,
  ClipboardList,
  Command,
  CreditCard,
  Database,
  FileText,
  Gauge,
  HeartPulse,
  Home,
  Inbox,
  LayoutDashboard,
  List,
  LockKeyhole,
  type LucideIcon,
  type LucideProps,
  Mail,
  Moon,
  Package,
  Play,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  Tags,
  Trash2,
  User,
  UserRoundCog,
  Users,
  Workflow,
  Wrench,
  X,
} from "lucide-react";

const icons: Record<IconName, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  "badge-dollar-sign": BadgeDollarSign,
  ban: Ban,
  "bar-chart": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  box: Box,
  boxes: Boxes,
  briefcase: BriefcaseBusiness,
  calendar: Calendar,
  check: Check,
  "circle-dollar-sign": CircleDollarSign,
  "circle-help": CircleHelp,
  "clipboard-list": ClipboardList,
  command: Command,
  "credit-card": CreditCard,
  database: Database,
  "file-text": FileText,
  gauge: Gauge,
  "heart-pulse": HeartPulse,
  home: Home,
  inbox: Inbox,
  "layout-dashboard": LayoutDashboard,
  list: List,
  lock: LockKeyhole,
  mail: Mail,
  moon: Moon,
  package: Package,
  play: Play,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  tags: Tags,
  "trash-2": Trash2,
  user: User,
  "user-cog": UserRoundCog,
  users: Users,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
};

export interface FlowpanelIconProps extends Omit<LucideProps, "ref"> {
  name: IconName;
}

/** Renders a server-component-safe icon name as a decorative Lucide SVG. */
export function FlowpanelIcon({ name, ...props }: FlowpanelIconProps) {
  const Icon = icons[name];
  if (!Icon) return null;
  return <Icon {...props} aria-hidden="true" focusable="false" data-flowpanel-icon={name} />;
}
