/**
 * One source of truth for the seed and the live feed, so a dashboard event
 * always names a product you can find in the catalog table.
 */
export interface CatalogProduct {
  /** Must match a name in `SCRAPERS` (seed-data.ts) — the seed maps it to an id. */
  scraper: string;
  title: string;
  brand: string;
  category: string;
  /** Integer USD cents. */
  priceCents: number;
  rating: number;
  reviews: number;
}

/** Marketplaces ScrapeAI crawls. Used to spread competitor listings across sites. */
export const SITES = ["amazon", "walmart", "ebay", "jumia", "mercadolibre", "flipkart"] as const;
export type Site = (typeof SITES)[number];

/** Seller names seen on marketplace listings (third-party + first-party; `null` = the marketplace itself). */
export const SELLERS = [
  "Marketplace Direct",
  "TechWorld",
  "GlobalMart",
  "PrimeDeals",
  "ElectroHub",
  "ValueStore",
  "MegaSeller",
  null,
] as const;

export const CATALOG: CatalogProduct[] = [
  // --- Amazon BSR — Electronics ---
  {
    scraper: "Amazon BSR — Electronics",
    title: "Apple AirPods Pro (2nd Generation) with USB-C",
    brand: "Apple",
    category: "Electronics",
    priceCents: 18900,
    rating: 4.8,
    reviews: 128492,
  },
  {
    scraper: "Amazon BSR — Electronics",
    title: "Echo Dot (5th Gen) Smart Speaker with Alexa",
    brand: "Amazon",
    category: "Electronics",
    priceCents: 4999,
    rating: 4.7,
    reviews: 94217,
  },
  {
    scraper: "Amazon BSR — Electronics",
    title: "Fire TV Stick 4K Max Streaming Device",
    brand: "Amazon",
    category: "Electronics",
    priceCents: 5999,
    rating: 4.6,
    reviews: 61038,
  },
  {
    scraper: "Amazon BSR — Electronics",
    title: 'Kindle Paperwhite (16 GB) 6.8" Display',
    brand: "Amazon",
    category: "Electronics",
    priceCents: 13999,
    rating: 4.7,
    reviews: 42870,
  },
  {
    scraper: "Amazon BSR — Electronics",
    title: "Sony WH-1000XM5 Wireless Noise-Cancelling Headphones",
    brand: "Sony",
    category: "Electronics",
    priceCents: 32800,
    rating: 4.6,
    reviews: 18654,
  },
  {
    scraper: "Amazon BSR — Electronics",
    title: "Anker 737 Power Bank (PowerCore 24K)",
    brand: "Anker",
    category: "Electronics",
    priceCents: 14999,
    rating: 4.7,
    reviews: 9921,
  },
  // --- Best Buy — GPU stock ---
  {
    scraper: "Best Buy — GPU stock",
    title: "NVIDIA GeForce RTX 4070 SUPER 12GB GDDR6X",
    brand: "NVIDIA",
    category: "Computers",
    priceCents: 59999,
    rating: 4.8,
    reviews: 3142,
  },
  {
    scraper: "Best Buy — GPU stock",
    title: "AMD Radeon RX 7800 XT 16GB Graphics Card",
    brand: "AMD",
    category: "Computers",
    priceCents: 49999,
    rating: 4.7,
    reviews: 2287,
  },
  {
    scraper: "Best Buy — GPU stock",
    title: "NVIDIA GeForce RTX 4090 24GB Founders Edition",
    brand: "NVIDIA",
    category: "Computers",
    priceCents: 159999,
    rating: 4.9,
    reviews: 1894,
  },
  {
    scraper: "Best Buy — GPU stock",
    title: "NVIDIA GeForce RTX 4060 8GB Dual Fan",
    brand: "NVIDIA",
    category: "Computers",
    priceCents: 29999,
    rating: 4.5,
    reviews: 5610,
  },
  // --- Newegg — daily deals ---
  {
    scraper: "Newegg — daily deals",
    title: "AMD Ryzen 7 9800X3D 8-Core Desktop Processor",
    brand: "AMD",
    category: "Computers",
    priceCents: 47900,
    rating: 4.9,
    reviews: 1203,
  },
  {
    scraper: "Newegg — daily deals",
    title: "WD Black SN850X 2TB NVMe SSD (Gen4)",
    brand: "Western Digital",
    category: "Computers",
    priceCents: 16499,
    rating: 4.8,
    reviews: 8740,
  },
  {
    scraper: "Newegg — daily deals",
    title: "Corsair Vengeance 32GB (2x16GB) DDR5-6000",
    brand: "Corsair",
    category: "Computers",
    priceCents: 11299,
    rating: 4.8,
    reviews: 6321,
  },
  // --- Etsy — handmade jewelry ---
  {
    scraper: "Etsy — handmade jewelry",
    title: "Raw Opal Ring, 14k Gold Fill, Handmade",
    brand: "LunaStoneCo",
    category: "Jewelry",
    priceCents: 6800,
    rating: 4.9,
    reviews: 2841,
  },
  {
    scraper: "Etsy — handmade jewelry",
    title: "Personalized Name Necklace, Sterling Silver",
    brand: "AuroraMade",
    category: "Jewelry",
    priceCents: 4200,
    rating: 4.8,
    reviews: 5129,
  },
  {
    scraper: "Etsy — handmade jewelry",
    title: "Birthstone Stacking Bracelet Set (3-Piece)",
    brand: "WillowAndOak",
    category: "Jewelry",
    priceCents: 3500,
    rating: 4.7,
    reviews: 1633,
  },
  // --- MediaMarkt — stock ---
  {
    scraper: "MediaMarkt — stock",
    title: 'LG OLED55C4 55" 4K OLED evo TV (2024)',
    brand: "LG",
    category: "Electronics",
    priceCents: 139900,
    rating: 4.8,
    reviews: 3412,
  },
  {
    scraper: "MediaMarkt — stock",
    title: "Dyson V15 Detect Absolute Cordless Vacuum",
    brand: "Dyson",
    category: "Home & Kitchen",
    priceCents: 64900,
    rating: 4.7,
    reviews: 9087,
  },
  {
    scraper: "MediaMarkt — stock",
    title: "Nintendo Switch OLED Model — White",
    brand: "Nintendo",
    category: "Toys & Games",
    priceCents: 34900,
    rating: 4.9,
    reviews: 27640,
  },
  // --- Idealo.de — price index ---
  {
    scraper: "Idealo.de — price index",
    title: "Samsung Galaxy S24 Ultra 512GB Titanium",
    brand: "Samsung",
    category: "Phones",
    priceCents: 119900,
    rating: 4.7,
    reviews: 14288,
  },
  {
    scraper: "Idealo.de — price index",
    title: "Apple iPhone 15 Pro 256GB Natural Titanium",
    brand: "Apple",
    category: "Phones",
    priceCents: 109900,
    rating: 4.8,
    reviews: 22104,
  },
  // --- Zalando — new arrivals ---
  {
    scraper: "Zalando — new arrivals",
    title: "Nike Air Force 1 '07 Sneakers — White",
    brand: "Nike",
    category: "Fashion",
    priceCents: 11495,
    rating: 4.8,
    reviews: 18420,
  },
  {
    scraper: "Zalando — new arrivals",
    title: "adidas Originals Samba OG Trainers",
    brand: "adidas",
    category: "Fashion",
    priceCents: 10000,
    rating: 4.7,
    reviews: 9633,
  },
  {
    scraper: "Zalando — new arrivals",
    title: "Levi's Quilted Puffer Jacket — Black",
    brand: "Levi's",
    category: "Fashion",
    priceCents: 12999,
    rating: 4.5,
    reviews: 1244,
  },
  // --- ASOS — sale ---
  {
    scraper: "ASOS — sale",
    title: "ASOS DESIGN Oversized T-Shirt (3-Pack)",
    brand: "ASOS DESIGN",
    category: "Fashion",
    priceCents: 2800,
    rating: 4.4,
    reviews: 6712,
  },
  {
    scraper: "ASOS — sale",
    title: "New Balance 530 Trainers — Silver",
    brand: "New Balance",
    category: "Fashion",
    priceCents: 9000,
    rating: 4.7,
    reviews: 4109,
  },
  // --- Kakaku.com — prices ---
  {
    scraper: "Kakaku.com — prices",
    title: "Sony Alpha 7 IV Full-Frame Mirrorless Camera",
    brand: "Sony",
    category: "Electronics",
    priceCents: 249800,
    rating: 4.9,
    reviews: 2873,
  },
  {
    scraper: "Kakaku.com — prices",
    title: "DJI Mini 4 Pro Drone (Fly More Combo)",
    brand: "DJI",
    category: "Electronics",
    priceCents: 119800,
    rating: 4.8,
    reviews: 1542,
  },
  // --- Flipkart — deals ---
  {
    scraper: "Flipkart — deals",
    title: "OnePlus 12 5G 256GB Flowy Emerald",
    brand: "OnePlus",
    category: "Phones",
    priceCents: 79900,
    rating: 4.6,
    reviews: 33180,
  },
  {
    scraper: "Flipkart — deals",
    title: "boAt Rockerz 450 Bluetooth On-Ear Headphones",
    brand: "boAt",
    category: "Electronics",
    priceCents: 1499,
    rating: 4.3,
    reviews: 215403,
  },
  // --- Jumia — phones ---
  {
    scraper: "Jumia — phones",
    title: "Tecno Spark 20 Pro 256GB Dual SIM",
    brand: "Tecno",
    category: "Phones",
    priceCents: 18500,
    rating: 4.2,
    reviews: 4880,
  },
  {
    scraper: "Jumia — phones",
    title: "Xiaomi Redmi 13C 128GB Navy Blue",
    brand: "Xiaomi",
    category: "Phones",
    priceCents: 14999,
    rating: 4.4,
    reviews: 7321,
  },
  // --- Amazon.ae — offers ---
  {
    scraper: "Amazon.ae — offers",
    title: "PlayStation 5 Console (Slim, Disc Edition)",
    brand: "Sony",
    category: "Toys & Games",
    priceCents: 49900,
    rating: 4.9,
    reviews: 41250,
  },
  {
    scraper: "Amazon.ae — offers",
    title: "Apple Watch Series 9 GPS 45mm Midnight",
    brand: "Apple",
    category: "Electronics",
    priceCents: 42900,
    rating: 4.8,
    reviews: 8190,
  },
  // --- Reddit — buildapcsales ---
  {
    scraper: "Reddit — buildapcsales",
    title: 'LG UltraGear 27GR95QE 27" OLED 240Hz Monitor',
    brand: "LG",
    category: "Computers",
    priceCents: 79999,
    rating: 4.7,
    reviews: 1422,
  },
  {
    scraper: "Reddit — buildapcsales",
    title: "NZXT H7 Flow ATX Mid Tower Case — Black",
    brand: "NZXT",
    category: "Computers",
    priceCents: 10499,
    rating: 4.8,
    reviews: 3201,
  },
  // --- JD.com — flash sales ---
  {
    scraper: "JD.com — flash sales",
    title: "Xiaomi Pad 6 128GB Tablet — Gravity Gray",
    brand: "Xiaomi",
    category: "Electronics",
    priceCents: 32900,
    rating: 4.6,
    reviews: 11904,
  },
  {
    scraper: "JD.com — flash sales",
    title: "Dreame X40 Ultra Robot Vacuum & Mop",
    brand: "Dreame",
    category: "Home & Kitchen",
    priceCents: 89900,
    rating: 4.7,
    reviews: 2618,
  },
  // --- Taobao — trends ---
  {
    scraper: "Taobao — trends",
    title: "Stanley Quencher H2.0 40oz Tumbler",
    brand: "Stanley",
    category: "Home & Kitchen",
    priceCents: 4500,
    rating: 4.8,
    reviews: 58210,
  },
  {
    scraper: "Taobao — trends",
    title: "POP MART Labubu Figure — Blind Box",
    brand: "POP MART",
    category: "Toys & Games",
    priceCents: 1599,
    rating: 4.6,
    reviews: 90412,
  },
  // --- Rakuten — deals ---
  {
    scraper: "Rakuten — deals",
    title: "Ergohuman Pro Ergonomic Mesh Office Chair",
    brand: "Ergohuman",
    category: "Home & Kitchen",
    priceCents: 49800,
    rating: 4.6,
    reviews: 1820,
  },
  // --- Alza.cz — electronics ---
  {
    scraper: "Alza.cz — electronics",
    title: "Logitech MX Master 3S Wireless Mouse",
    brand: "Logitech",
    category: "Computers",
    priceCents: 9999,
    rating: 4.8,
    reviews: 24710,
  },
  {
    scraper: "Alza.cz — electronics",
    title: "Keychron K2 Wireless Mechanical Keyboard",
    brand: "Keychron",
    category: "Computers",
    priceCents: 8900,
    rating: 4.7,
    reviews: 6044,
  },
  // --- Mercado Livre — prices ---
  {
    scraper: "Mercado Livre — prices",
    title: "Motorola Moto G84 5G 256GB Vegan Leather",
    brand: "Motorola",
    category: "Phones",
    priceCents: 24999,
    rating: 4.5,
    reviews: 13288,
  },
  {
    scraper: "Mercado Livre — prices",
    title: "Mondial Air Fryer 4L Family Inox",
    brand: "Mondial",
    category: "Home & Kitchen",
    priceCents: 5990,
    rating: 4.6,
    reviews: 42019,
  },
];
