/**
 * Canonical sample of scraped products for the ScrapeAI demo.
 *
 * One source of truth, imported by two consumers so they never drift:
 *   - `scripts/seed-data.ts` inserts these as durable `products` rows.
 *   - `src/lib/live-feed.ts` references them in the in-memory live activity
 *     feed, so an "extracted …" event on the dashboard names a product you
 *     can actually find in the catalog table.
 *
 * `scraper` matches a name in `SCRAPERS` (seed-data.ts) so the seed can map
 * each product to its scraper id. Prices are integer USD cents.
 */
export interface CatalogProduct {
  /** Name of the owning scraper — must match a row in `SCRAPERS`. */
  scraper: string;
  asin: string;
  title: string;
  brand: string;
  category: string;
  priceCents: number;
  rating: number;
  reviews: number;
  stock: "in_stock" | "low_stock" | "out_of_stock";
  url: string;
}

/** Marketplaces ScrapeAI crawls. Used to spread competitor listings across sites. */
export const SITES = ["amazon", "walmart", "ebay", "jumia", "mercadolibre", "flipkart"] as const;
export type Site = (typeof SITES)[number];

/** Seller names seen on marketplace listings (third-party + first-party; `null` = the marketplace itself). */
export const SELLERS = [
  "Marketplace Direct",
  "TechWorld",
  "GlobalMart",
  "PrimeDeals",
  "ElectroHub",
  "ValueStore",
  "MegaSeller",
  null,
] as const;

const amazon = (asin: string) => `https://www.amazon.com/dp/${asin}`;

export const CATALOG: CatalogProduct[] = [
  // --- Amazon BSR — Electronics ---
  {
    scraper: "Amazon BSR — Electronics",
    asin: "B0CHWRXH8B",
    title: "Apple AirPods Pro (2nd Generation) with USB-C",
    brand: "Apple",
    category: "Electronics",
    priceCents: 18900,
    rating: 4.8,
    reviews: 128492,
    stock: "in_stock",
    url: amazon("B0CHWRXH8B"),
  },
  {
    scraper: "Amazon BSR — Electronics",
    asin: "B09B8V1LZ3",
    title: "Echo Dot (5th Gen) Smart Speaker with Alexa",
    brand: "Amazon",
    category: "Electronics",
    priceCents: 4999,
    rating: 4.7,
    reviews: 94217,
    stock: "in_stock",
    url: amazon("B09B8V1LZ3"),
  },
  {
    scraper: "Amazon BSR — Electronics",
    asin: "B0BDHB9Y8H",
    title: "Fire TV Stick 4K Max Streaming Device",
    brand: "Amazon",
    category: "Electronics",
    priceCents: 5999,
    rating: 4.6,
    reviews: 61038,
    stock: "low_stock",
    url: amazon("B0BDHB9Y8H"),
  },
  {
    scraper: "Amazon BSR — Electronics",
    asin: "B0BJLPGND4",
    title: 'Kindle Paperwhite (16 GB) 6.8" Display',
    brand: "Amazon",
    category: "Electronics",
    priceCents: 13999,
    rating: 4.7,
    reviews: 42870,
    stock: "in_stock",
    url: amazon("B0BJLPGND4"),
  },
  {
    scraper: "Amazon BSR — Electronics",
    asin: "B0C7KMR9TT",
    title: "Sony WH-1000XM5 Wireless Noise-Cancelling Headphones",
    brand: "Sony",
    category: "Electronics",
    priceCents: 32800,
    rating: 4.6,
    reviews: 18654,
    stock: "in_stock",
    url: amazon("B0C7KMR9TT"),
  },
  {
    scraper: "Amazon BSR — Electronics",
    asin: "B0CSWYCG3F",
    title: "Anker 737 Power Bank (PowerCore 24K)",
    brand: "Anker",
    category: "Electronics",
    priceCents: 14999,
    rating: 4.7,
    reviews: 9921,
    stock: "low_stock",
    url: amazon("B0CSWYCG3F"),
  },
  // --- Best Buy — GPU stock ---
  {
    scraper: "Best Buy — GPU stock",
    asin: "BB-RTX4070S",
    title: "NVIDIA GeForce RTX 4070 SUPER 12GB GDDR6X",
    brand: "NVIDIA",
    category: "Computers",
    priceCents: 59999,
    rating: 4.8,
    reviews: 3142,
    stock: "out_of_stock",
    url: "https://www.bestbuy.com/site/rtx-4070-super",
  },
  {
    scraper: "Best Buy — GPU stock",
    asin: "BB-RX7800XT",
    title: "AMD Radeon RX 7800 XT 16GB Graphics Card",
    brand: "AMD",
    category: "Computers",
    priceCents: 49999,
    rating: 4.7,
    reviews: 2287,
    stock: "in_stock",
    url: "https://www.bestbuy.com/site/rx-7800-xt",
  },
  {
    scraper: "Best Buy — GPU stock",
    asin: "BB-RTX4090",
    title: "NVIDIA GeForce RTX 4090 24GB Founders Edition",
    brand: "NVIDIA",
    category: "Computers",
    priceCents: 159999,
    rating: 4.9,
    reviews: 1894,
    stock: "out_of_stock",
    url: "https://www.bestbuy.com/site/rtx-4090",
  },
  {
    scraper: "Best Buy — GPU stock",
    asin: "BB-RTX4060",
    title: "NVIDIA GeForce RTX 4060 8GB Dual Fan",
    brand: "NVIDIA",
    category: "Computers",
    priceCents: 29999,
    rating: 4.5,
    reviews: 5610,
    stock: "in_stock",
    url: "https://www.bestbuy.com/site/rtx-4060",
  },
  // --- Newegg — daily deals ---
  {
    scraper: "Newegg — daily deals",
    asin: "NE-9800X3D",
    title: "AMD Ryzen 7 9800X3D 8-Core Desktop Processor",
    brand: "AMD",
    category: "Computers",
    priceCents: 47900,
    rating: 4.9,
    reviews: 1203,
    stock: "low_stock",
    url: "https://www.newegg.com/p/ryzen-7-9800x3d",
  },
  {
    scraper: "Newegg — daily deals",
    asin: "NE-SN850X2T",
    title: "WD Black SN850X 2TB NVMe SSD (Gen4)",
    brand: "Western Digital",
    category: "Computers",
    priceCents: 16499,
    rating: 4.8,
    reviews: 8740,
    stock: "in_stock",
    url: "https://www.newegg.com/p/wd-black-sn850x-2tb",
  },
  {
    scraper: "Newegg — daily deals",
    asin: "NE-DDR5-32",
    title: "Corsair Vengeance 32GB (2x16GB) DDR5-6000",
    brand: "Corsair",
    category: "Computers",
    priceCents: 11299,
    rating: 4.8,
    reviews: 6321,
    stock: "in_stock",
    url: "https://www.newegg.com/p/corsair-vengeance-ddr5",
  },
  // --- Etsy — handmade jewelry ---
  {
    scraper: "Etsy — handmade jewelry",
    asin: "ET-OPAL-RNG",
    title: "Raw Opal Ring, 14k Gold Fill, Handmade",
    brand: "LunaStoneCo",
    category: "Jewelry",
    priceCents: 6800,
    rating: 4.9,
    reviews: 2841,
    stock: "in_stock",
    url: "https://www.etsy.com/listing/opal-ring",
  },
  {
    scraper: "Etsy — handmade jewelry",
    asin: "ET-NAME-NCK",
    title: "Personalized Name Necklace, Sterling Silver",
    brand: "AuroraMade",
    category: "Jewelry",
    priceCents: 4200,
    rating: 4.8,
    reviews: 5129,
    stock: "in_stock",
    url: "https://www.etsy.com/listing/name-necklace",
  },
  {
    scraper: "Etsy — handmade jewelry",
    asin: "ET-BIRTH-BR",
    title: "Birthstone Stacking Bracelet Set (3-Piece)",
    brand: "WillowAndOak",
    category: "Jewelry",
    priceCents: 3500,
    rating: 4.7,
    reviews: 1633,
    stock: "low_stock",
    url: "https://www.etsy.com/listing/birthstone-bracelet",
  },
  // --- MediaMarkt — stock ---
  {
    scraper: "MediaMarkt — stock",
    asin: "MM-LG-C4-55",
    title: 'LG OLED55C4 55" 4K OLED evo TV (2024)',
    brand: "LG",
    category: "Electronics",
    priceCents: 139900,
    rating: 4.8,
    reviews: 3412,
    stock: "in_stock",
    url: "https://www.mediamarkt.de/de/product/lg-oled55c4",
  },
  {
    scraper: "MediaMarkt — stock",
    asin: "MM-DYSON-V15",
    title: "Dyson V15 Detect Absolute Cordless Vacuum",
    brand: "Dyson",
    category: "Home & Kitchen",
    priceCents: 64900,
    rating: 4.7,
    reviews: 9087,
    stock: "low_stock",
    url: "https://www.mediamarkt.de/de/product/dyson-v15-detect",
  },
  {
    scraper: "MediaMarkt — stock",
    asin: "MM-NSW-OLED",
    title: "Nintendo Switch OLED Model — White",
    brand: "Nintendo",
    category: "Toys & Games",
    priceCents: 34900,
    rating: 4.9,
    reviews: 27640,
    stock: "in_stock",
    url: "https://www.mediamarkt.de/de/product/nintendo-switch-oled",
  },
  // --- Idealo.de — price index ---
  {
    scraper: "Idealo.de — price index",
    asin: "ID-S24U-512",
    title: "Samsung Galaxy S24 Ultra 512GB Titanium",
    brand: "Samsung",
    category: "Phones",
    priceCents: 119900,
    rating: 4.7,
    reviews: 14288,
    stock: "in_stock",
    url: "https://www.idealo.de/preisvergleich/samsung-galaxy-s24-ultra",
  },
  {
    scraper: "Idealo.de — price index",
    asin: "ID-IPH15P",
    title: "Apple iPhone 15 Pro 256GB Natural Titanium",
    brand: "Apple",
    category: "Phones",
    priceCents: 109900,
    rating: 4.8,
    reviews: 22104,
    stock: "low_stock",
    url: "https://www.idealo.de/preisvergleich/iphone-15-pro",
  },
  // --- Zalando — new arrivals ---
  {
    scraper: "Zalando — new arrivals",
    asin: "ZA-NK-AF1",
    title: "Nike Air Force 1 '07 Sneakers — White",
    brand: "Nike",
    category: "Fashion",
    priceCents: 11495,
    rating: 4.8,
    reviews: 18420,
    stock: "in_stock",
    url: "https://www.zalando.com/nike-air-force-1-07",
  },
  {
    scraper: "Zalando — new arrivals",
    asin: "ZA-AD-SAMBA",
    title: "adidas Originals Samba OG Trainers",
    brand: "adidas",
    category: "Fashion",
    priceCents: 10000,
    rating: 4.7,
    reviews: 9633,
    stock: "low_stock",
    url: "https://www.zalando.com/adidas-samba-og",
  },
  {
    scraper: "Zalando — new arrivals",
    asin: "ZA-LV-PUFFER",
    title: "Levi's Quilted Puffer Jacket — Black",
    brand: "Levi's",
    category: "Fashion",
    priceCents: 12999,
    rating: 4.5,
    reviews: 1244,
    stock: "in_stock",
    url: "https://www.zalando.com/levis-puffer-jacket",
  },
  // --- ASOS — sale ---
  {
    scraper: "ASOS — sale",
    asin: "AS-DESIGN-TEE",
    title: "ASOS DESIGN Oversized T-Shirt (3-Pack)",
    brand: "ASOS DESIGN",
    category: "Fashion",
    priceCents: 2800,
    rating: 4.4,
    reviews: 6712,
    stock: "in_stock",
    url: "https://www.asos.com/asos-design-oversized-tee",
  },
  {
    scraper: "ASOS — sale",
    asin: "AS-NB-530",
    title: "New Balance 530 Trainers — Silver",
    brand: "New Balance",
    category: "Fashion",
    priceCents: 9000,
    rating: 4.7,
    reviews: 4109,
    stock: "low_stock",
    url: "https://www.asos.com/new-balance-530",
  },
  // --- Kakaku.com — prices ---
  {
    scraper: "Kakaku.com — prices",
    asin: "KK-SONY-A7IV",
    title: "Sony Alpha 7 IV Full-Frame Mirrorless Camera",
    brand: "Sony",
    category: "Electronics",
    priceCents: 249800,
    rating: 4.9,
    reviews: 2873,
    stock: "in_stock",
    url: "https://kakaku.com/item/sony-alpha-7-iv",
  },
  {
    scraper: "Kakaku.com — prices",
    asin: "KK-DJI-MINI4",
    title: "DJI Mini 4 Pro Drone (Fly More Combo)",
    brand: "DJI",
    category: "Electronics",
    priceCents: 119800,
    rating: 4.8,
    reviews: 1542,
    stock: "low_stock",
    url: "https://kakaku.com/item/dji-mini-4-pro",
  },
  // --- Flipkart — deals ---
  {
    scraper: "Flipkart — deals",
    asin: "FK-OP12-256",
    title: "OnePlus 12 5G 256GB Flowy Emerald",
    brand: "OnePlus",
    category: "Phones",
    priceCents: 79900,
    rating: 4.6,
    reviews: 33180,
    stock: "in_stock",
    url: "https://www.flipkart.com/oneplus-12-5g",
  },
  {
    scraper: "Flipkart — deals",
    asin: "FK-BOAT-RW",
    title: "boAt Rockerz 450 Bluetooth On-Ear Headphones",
    brand: "boAt",
    category: "Electronics",
    priceCents: 1499,
    rating: 4.3,
    reviews: 215403,
    stock: "in_stock",
    url: "https://www.flipkart.com/boat-rockerz-450",
  },
  // --- Jumia — phones ---
  {
    scraper: "Jumia — phones",
    asin: "JU-TECNO-S20",
    title: "Tecno Spark 20 Pro 256GB Dual SIM",
    brand: "Tecno",
    category: "Phones",
    priceCents: 18500,
    rating: 4.2,
    reviews: 4880,
    stock: "in_stock",
    url: "https://www.jumia.co.ke/tecno-spark-20-pro",
  },
  {
    scraper: "Jumia — phones",
    asin: "JU-XIAOMI-13C",
    title: "Xiaomi Redmi 13C 128GB Navy Blue",
    brand: "Xiaomi",
    category: "Phones",
    priceCents: 14999,
    rating: 4.4,
    reviews: 7321,
    stock: "low_stock",
    url: "https://www.jumia.co.ke/xiaomi-redmi-13c",
  },
  // --- Amazon.ae — offers ---
  {
    scraper: "Amazon.ae — offers",
    asin: "B08H93ZRK9",
    title: "PlayStation 5 Console (Slim, Disc Edition)",
    brand: "Sony",
    category: "Toys & Games",
    priceCents: 49900,
    rating: 4.9,
    reviews: 41250,
    stock: "out_of_stock",
    url: "https://www.amazon.ae/dp/B08H93ZRK9",
  },
  {
    scraper: "Amazon.ae — offers",
    asin: "B0BSHF7WHW",
    title: "Apple Watch Series 9 GPS 45mm Midnight",
    brand: "Apple",
    category: "Electronics",
    priceCents: 42900,
    rating: 4.8,
    reviews: 8190,
    stock: "in_stock",
    url: "https://www.amazon.ae/dp/B0BSHF7WHW",
  },
  // --- Reddit — buildapcsales ---
  {
    scraper: "Reddit — buildapcsales",
    asin: "RD-LG-27GR",
    title: 'LG UltraGear 27GR95QE 27" OLED 240Hz Monitor',
    brand: "LG",
    category: "Computers",
    priceCents: 79999,
    rating: 4.7,
    reviews: 1422,
    stock: "low_stock",
    url: "https://www.reddit.com/r/buildapcsales/lg-27gr95qe",
  },
  {
    scraper: "Reddit — buildapcsales",
    asin: "RD-NZXT-H7",
    title: "NZXT H7 Flow ATX Mid Tower Case — Black",
    brand: "NZXT",
    category: "Computers",
    priceCents: 10499,
    rating: 4.8,
    reviews: 3201,
    stock: "in_stock",
    url: "https://www.reddit.com/r/buildapcsales/nzxt-h7-flow",
  },
  // --- JD.com — flash sales ---
  {
    scraper: "JD.com — flash sales",
    asin: "JD-MI-PAD6",
    title: "Xiaomi Pad 6 128GB Tablet — Gravity Gray",
    brand: "Xiaomi",
    category: "Electronics",
    priceCents: 32900,
    rating: 4.6,
    reviews: 11904,
    stock: "in_stock",
    url: "https://www.jd.com/product/xiaomi-pad-6",
  },
  {
    scraper: "JD.com — flash sales",
    asin: "JD-DREAME-X40",
    title: "Dreame X40 Ultra Robot Vacuum & Mop",
    brand: "Dreame",
    category: "Home & Kitchen",
    priceCents: 89900,
    rating: 4.7,
    reviews: 2618,
    stock: "low_stock",
    url: "https://www.jd.com/product/dreame-x40-ultra",
  },
  // --- Taobao — trends ---
  {
    scraper: "Taobao — trends",
    asin: "TB-STANLEY-Q",
    title: "Stanley Quencher H2.0 40oz Tumbler",
    brand: "Stanley",
    category: "Home & Kitchen",
    priceCents: 4500,
    rating: 4.8,
    reviews: 58210,
    stock: "in_stock",
    url: "https://www.taobao.com/item/stanley-quencher",
  },
  {
    scraper: "Taobao — trends",
    asin: "TB-LABUBU",
    title: "POP MART Labubu Figure — Blind Box",
    brand: "POP MART",
    category: "Toys & Games",
    priceCents: 1599,
    rating: 4.6,
    reviews: 90412,
    stock: "out_of_stock",
    url: "https://www.taobao.com/item/popmart-labubu",
  },
  // --- Rakuten — deals ---
  {
    scraper: "Rakuten — deals",
    asin: "RK-DESK-CHAIR",
    title: "Ergohuman Pro Ergonomic Mesh Office Chair",
    brand: "Ergohuman",
    category: "Home & Kitchen",
    priceCents: 49800,
    rating: 4.6,
    reviews: 1820,
    stock: "in_stock",
    url: "https://www.rakuten.co.jp/item/ergohuman-pro",
  },
  // --- Alza.cz — electronics ---
  {
    scraper: "Alza.cz — electronics",
    asin: "AL-LOGI-MX3S",
    title: "Logitech MX Master 3S Wireless Mouse",
    brand: "Logitech",
    category: "Computers",
    priceCents: 9999,
    rating: 4.8,
    reviews: 24710,
    stock: "in_stock",
    url: "https://www.alza.cz/logitech-mx-master-3s",
  },
  {
    scraper: "Alza.cz — electronics",
    asin: "AL-KEYCHRON-K2",
    title: "Keychron K2 Wireless Mechanical Keyboard",
    brand: "Keychron",
    category: "Computers",
    priceCents: 8900,
    rating: 4.7,
    reviews: 6044,
    stock: "low_stock",
    url: "https://www.alza.cz/keychron-k2",
  },
  // --- Mercado Livre — prices ---
  {
    scraper: "Mercado Livre — prices",
    asin: "ML-MOTO-G84",
    title: "Motorola Moto G84 5G 256GB Vegan Leather",
    brand: "Motorola",
    category: "Phones",
    priceCents: 24999,
    rating: 4.5,
    reviews: 13288,
    stock: "in_stock",
    url: "https://www.mercadolivre.com.br/moto-g84-5g",
  },
  {
    scraper: "Mercado Livre — prices",
    asin: "ML-AIRFRYER",
    title: "Mondial Air Fryer 4L Family Inox",
    brand: "Mondial",
    category: "Home & Kitchen",
    priceCents: 5990,
    rating: 4.6,
    reviews: 42019,
    stock: "in_stock",
    url: "https://www.mercadolivre.com.br/mondial-air-fryer",
  },
];
