import { describe, expect, it, vi } from "vitest";
import { defineFlowPanel } from "../defineFlowPanel";
import { defineResource } from "../resource/defineResource";
import type { ModelMetadata } from "../resource/types";

const userMeta: ModelMetadata = {
  name: "User",
  primaryKey: "id",
  fields: [
    {
      name: "id",
      type: "int",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: true,
      isAutoGenerated: true,
    },
    {
      name: "email",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "plan",
      type: "enum",
      kind: "enum",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
      enumValues: ["free", "pro"],
    },
  ],
};

type UserTable = { id: number; email: string; plan: "free" | "pro" };

/** Stub shaped like drizzleAdapter/prismaAdapter output — `{ sql, resource }`. */
function stubAdapter(): unknown {
  return {
    sql: {
      execute: vi.fn().mockResolvedValue([]),
      transaction: vi.fn(),
      dialect: "postgres" as const,
    },
    resource: {
      getModelNames: () => ["User"],
      getModelMetadata: () => userMeta,
      getEnumValues: () => [],
      findMany: vi.fn().mockResolvedValue({ data: [], total: 0 }),
      findUnique: vi.fn().mockResolvedValue(null),
      count: vi.fn().mockResolvedValue(0),
      create: vi.fn().mockResolvedValue({}),
      update: vi.fn().mockResolvedValue({}),
      delete: vi.fn().mockResolvedValue({}),
    },
  };
}

const baseConfig = {
  appName: "Test",
  timezone: "UTC",
  basePath: "/admin",
  pipeline: { stages: ["a"] as const, fields: {}, stageFields: { a: {} } },
  security: {
    auth: {
      getSession: async () => ({ _flowpanelStub: true as const, id: "dev", role: "admin" }),
    },
  },
};

describe("defineFlowPanel — TypedResourceDefinition integration", () => {
  it("lowers a typed resource into the resources map", () => {
    const user = defineResource<UserTable>(userMeta, {
      label: "User",
      columns: (u) => [u.id, u.email, u.plan],
      filters: (u) => [u.plan],
      actions: {
        promote: { type: "row", label: "Promote", run: () => {} },
      },
    });

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: stubAdapter(),
      resources: { user },
      // biome-ignore lint/suspicious/noExplicitAny: test stub — config shape is runtime-validated
    } as any);

    const res = fp.resources?.user;
    expect(res).toBeDefined();
    if (!res) throw new Error("unreachable");
    expect(res.label).toBe("User");
    expect(res.columns.map((c) => c.id)).toEqual(["id", "email", "plan"]);
    expect(res.filters[0]!.mode).toBe("enum");
    expect(res.actions[0]!.type).toBe("mutation");
  });

  it("propagates realtime + drawer flags from the typed builder", () => {
    const user = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id],
      drawer: "userActivity",
      realtime: true,
    });

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: stubAdapter(),
      resources: { user },
      // biome-ignore lint/suspicious/noExplicitAny: test stub — config shape is runtime-validated
    } as any);

    const res = fp.resources?.user as
      | (NonNullable<typeof fp.resources>["user"] & { _realtime: boolean; _drawer?: string })
      | undefined;
    expect(res).toBeDefined();
    if (!res) throw new Error("unreachable");
    expect(res._realtime).toBe(true);
    expect(res._drawer).toBe("userActivity");
  });
});
