import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import type { SerializedColumn, FieldMetadata } from "@flowpanel/core";
import { CellRenderer } from "../resource/cells";
import { FieldWidget } from "../resource/fields";

afterEach(cleanup);

const column: SerializedColumn = {
  id: "status",
  path: "status",
  label: "Status",
  type: "field",
  format: "auto",
  opts: {},
};

describe("CellRenderer render-prop", () => {
  it("falls back to dispatcher when no render is provided", () => {
    render(<CellRenderer column={column} value="active" row={{ status: "active" }} />);
    expect(screen.getByText("active")).toBeInTheDocument();
  });

  it("calls render and uses its output when provided", () => {
    const renderFn = vi.fn((v: unknown, row: Record<string, unknown>) => (
      <span data-testid="custom-cell">
        {String(v)}-{String(row.id)}
      </span>
    ));
    render(
      <CellRenderer
        column={column}
        value="active"
        row={{ id: 42, status: "active" }}
        render={renderFn}
      />,
    );
    expect(screen.getByTestId("custom-cell")).toHaveTextContent("active-42");
    expect(renderFn).toHaveBeenCalledWith("active", { id: 42, status: "active" });
  });

  it("receives null/undefined values (consumer handles fallback)", () => {
    const renderFn = vi.fn((v: unknown) => (v === null ? <em>empty</em> : <>{String(v)}</>));
    render(<CellRenderer column={column} value={null} row={{}} render={renderFn} />);
    expect(screen.getByText("empty")).toBeInTheDocument();
    expect(renderFn).toHaveBeenCalledWith(null, {});
  });

  it("falls through to dispatcher when render returns undefined", () => {
    const renderFn = vi.fn(() => undefined);
    render(
      <CellRenderer column={column} value="active" row={{ status: "active" }} render={renderFn} />,
    );
    // Default dispatcher kicks in — renders "active" as text
    expect(screen.getByText("active")).toBeInTheDocument();
    expect(renderFn).toHaveBeenCalled();
  });
});

describe("FieldWidget render-prop", () => {
  const meta: FieldMetadata = {
    name: "bio",
    type: "string",
    kind: "scalar",
    isRequired: false,
    isList: false,
    isId: false,
    isAutoGenerated: false,
  };

  it("falls back to type-based dispatcher when no render is provided", () => {
    render(<FieldWidget name="bio" label="Bio" value="hello" onChange={() => {}} meta={meta} />);
    // Default dispatcher uses TextField; input should exist
    expect(screen.getByDisplayValue("hello")).toBeInTheDocument();
  });

  it("uses render output when provided", () => {
    const renderFn = vi.fn((props: { value: unknown }) => (
      <div data-testid="rich-text">{String(props.value)}</div>
    ));
    render(
      <FieldWidget
        name="bio"
        label="Bio"
        value="rich content"
        onChange={() => {}}
        meta={meta}
        render={renderFn}
      />,
    );
    expect(screen.getByTestId("rich-text")).toHaveTextContent("rich content");
  });

  it("falls through to dispatcher when render returns undefined", () => {
    const renderFn = vi.fn(() => undefined);
    render(
      <FieldWidget
        name="bio"
        label="Bio"
        value="hello"
        onChange={() => {}}
        meta={meta}
        render={renderFn}
      />,
    );
    expect(screen.getByDisplayValue("hello")).toBeInTheDocument();
  });
});
