import { describe, expect, it, vi } from "vitest";
import { isColumnRef, isComputedColumnInput, makeColumnRef } from "../columnRefs";
import { defineResource } from "../defineResource";
import { createTableProxy } from "../tableProxy";
import type { FieldMetadata, ModelMetadata } from "../types";

/**
 * A synthetic "table type" paired with `userMeta`. In real use TTable comes
 * from a Drizzle table or Prisma delegate; the tests use an explicit shape
 * so `defineResource<UserTable>(userMeta, ...)` types the selector correctly.
 */
type UserTable = {
  id: number;
  email: string;
  plan: "free" | "pro";
  category: { id: number; name: string } | null;
};

const userMeta: ModelMetadata = {
  name: "User",
  tableName: "users",
  primaryKey: "id",
  fields: [
    {
      name: "id",
      type: "int",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: true,
      isAutoGenerated: true,
    },
    {
      name: "email",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "plan",
      type: "enum",
      kind: "enum",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
      enumValues: ["free", "pro"],
    },
    {
      name: "category",
      type: "relation",
      kind: "relation",
      isRequired: false,
      isList: false,
      isId: false,
      isAutoGenerated: false,
      relationModel: "Category",
    },
  ] satisfies FieldMetadata[],
};

describe("ColumnRef", () => {
  it("marks values as ColumnRef via branded symbol", () => {
    const ref = makeColumnRef("email", {
      name: "email",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    });
    expect(isColumnRef(ref)).toBe(true);
    expect(isColumnRef({ path: "email" })).toBe(false);
    expect(isColumnRef(null)).toBe(false);
    expect(isColumnRef("email")).toBe(false);
  });

  it("exposes path + metadata verbatim", () => {
    const ref = makeColumnRef("user.email", {
      name: "email",
      type: "string",
      kind: "scalar",
      isRequired: false,
      isList: false,
      isId: false,
      isAutoGenerated: false,
      enumValues: ["a", "b"],
    });
    expect(ref.path).toBe("user.email");
    expect(ref.metadata.type).toBe("string");
    expect(ref.metadata.enumValues).toEqual(["a", "b"]);
  });

  it("is frozen — cannot be mutated by consumers", () => {
    const ref = makeColumnRef("id", {
      name: "id",
      type: "int",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: true,
      isAutoGenerated: true,
    });
    expect(Object.isFrozen(ref)).toBe(true);
  });
});

describe("createTableProxy", () => {
  it("returns a ColumnRef for scalar property access", () => {
    const proxy = createTableProxy<UserTable>(userMeta);
    const ref = proxy.email;
    expect(isColumnRef(ref)).toBe(true);
    expect(ref.path).toBe("email");
    expect(ref.metadata.type).toBe("string");
  });

  it("surfaces enum metadata on the ref", () => {
    const proxy = createTableProxy<UserTable>(userMeta);
    expect(proxy.plan.metadata.enumValues).toEqual(["free", "pro"]);
  });

  it("returns a relation ref", () => {
    const proxy = createTableProxy<UserTable>(userMeta);
    const ref = proxy.category;
    expect(ref.metadata.kind).toBe("relation");
    expect(ref.metadata.relationModel).toBe("Category");
  });

  it("throws with a helpful message on unknown column", () => {
    const proxy = createTableProxy<UserTable>(userMeta);
    expect(
      () =>
        // @ts-expect-error — runtime test that unknown column throws
        proxy.nonexistent,
    ).toThrow(/no column "nonexistent".*email/);
  });

  it("caches refs so identity checks are stable", () => {
    const proxy = createTableProxy<UserTable>(userMeta);
    expect(proxy.email).toBe(proxy.email);
  });
});

describe("ComputedColumnInput", () => {
  it("detects a computed column by id + compute", () => {
    expect(
      isComputedColumnInput({
        id: "totalPaid",
        label: "Total",
        compute: () => 0,
      }),
    ).toBe(true);
  });

  it("detects a computeBatch form", () => {
    expect(
      isComputedColumnInput({
        id: "totalPaid",
        computeBatch: () => new Map(),
      }),
    ).toBe(true);
  });

  it("rejects objects without compute/computeBatch", () => {
    expect(isComputedColumnInput({ id: "foo" })).toBe(false);
    expect(isComputedColumnInput({ compute: () => 0 })).toBe(false);
    expect(isComputedColumnInput(null)).toBe(false);
  });
});

// ───────────────────────────────────────────────────────────────────────────
// defineResource
// ───────────────────────────────────────────────────────────────────────────

describe("defineResource — core shape", () => {
  it("materializes field columns from the selector", () => {
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id, u.email, u.plan],
    });
    expect(r.kind).toBe("typed-resource");
    expect(r.model).toBe("User");
    expect(r.primaryKey).toBe("id");
    expect(r.columns.map((c) => c.id)).toEqual(["id", "email", "plan"]);
    expect(r.columns.every((c) => c.kind === "field")).toBe(true);
  });

  it("surfaces enum values on field columns", () => {
    const r = defineResource<UserTable>(userMeta, { columns: (u) => [u.plan] });
    const plan = r.columns[0]!;
    expect(plan.kind).toBe("field");
    if (plan.kind !== "field") throw new Error("unreachable");
    expect(plan.enumValues).toEqual(["free", "pro"]);
  });

  it("defaults label + labelPlural from metadata name", () => {
    const r = defineResource<UserTable>(userMeta, { columns: (u) => [u.id] });
    expect(r.label).toBe("User");
    expect(r.labelPlural).toBe("Users");
  });

  it("respects explicit label + labelPlural", () => {
    const r = defineResource<UserTable>(userMeta, {
      label: "Person",
      labelPlural: "People",
      columns: (u) => [u.id],
    });
    expect(r.label).toBe("Person");
    expect(r.labelPlural).toBe("People");
  });

  it("pluralizes 'category' → 'categories' (y-stem rule)", () => {
    const categoryMeta: ModelMetadata = {
      name: "Category",
      primaryKey: "id",
      fields: [
        {
          name: "id",
          type: "int",
          kind: "scalar",
          isRequired: true,
          isList: false,
          isId: true,
          isAutoGenerated: true,
        },
      ],
    };
    const r = defineResource<{ id: number }>(categoryMeta, { columns: (c) => [c.id] });
    expect(r.labelPlural).toBe("Categories");
  });

  it("accepts an inline computed column", () => {
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [
        u.email,
        {
          id: "totalPaid",
          label: "Total paid",
          format: "currency" as const,
          compute: () => 0,
        },
      ],
    });
    expect(r.columns).toHaveLength(2);
    expect(r.columns[1]!.kind).toBe("computed");
    expect(r.columns[1]!.id).toBe("totalPaid");
  });

  it("preserves computeBatch to avoid N+1 on lists", async () => {
    const batch = vi.fn(async () => new Map([[1, 100]]));
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id, { id: "totalPaid", computeBatch: batch }],
    });
    const col = r.columns[1]!;
    if (col.kind !== "computed") throw new Error("unreachable");
    expect(col.computeBatch).toBeDefined();
    await col.computeBatch!({
      rows: [{ id: 1, email: "a@b.c", plan: "free", category: null }],
      db: null,
      session: null,
    });
    expect(batch).toHaveBeenCalledOnce();
  });

  it("forwards drawer / realtime / export flags", () => {
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id],
      drawer: "userActivity",
      realtime: true,
      export: true,
    });
    expect(r.drawer).toBe("userActivity");
    expect(r.realtime).toBe(true);
    expect(r.export).toBe(true);
  });

  it("throws on an unknown column in the selector", () => {
    expect(() =>
      defineResource<UserTable>(userMeta, {
        // @ts-expect-error — typo is rejected at compile time AND runtime
        columns: (u) => [u.nonexistent],
      }),
    ).toThrow(/no column "nonexistent"/);
  });
});

describe("defineResource — filters", () => {
  // Extend UserTable + meta with booleans/dates/numbers for filter coverage.
  type ExtTable = UserTable & {
    archived: boolean;
    createdAt: Date;
    priceUsd: number;
  };
  const extMeta: ModelMetadata = {
    ...userMeta,
    fields: [
      ...userMeta.fields,
      {
        name: "archived",
        type: "boolean",
        kind: "scalar",
        isRequired: true,
        isList: false,
        isId: false,
        isAutoGenerated: false,
      },
      {
        name: "createdAt",
        type: "datetime",
        kind: "scalar",
        isRequired: true,
        isList: false,
        isId: false,
        isAutoGenerated: true,
      },
      {
        name: "priceUsd",
        type: "int",
        kind: "scalar",
        isRequired: false,
        isList: false,
        isId: false,
        isAutoGenerated: false,
      },
    ],
  };

  it("infers enum mode + surfaces options from column metadata", () => {
    const r = defineResource<ExtTable>(extMeta, {
      columns: (u) => [u.id],
      filters: (u) => [u.plan],
    });
    expect(r.filters[0]!.mode).toBe("enum");
    expect(r.filters[0]!.opts.options).toEqual(["free", "pro"]);
  });

  it("infers text mode for strings", () => {
    const r = defineResource<ExtTable>(extMeta, {
      columns: (u) => [u.id],
      filters: (u) => [u.email],
    });
    expect(r.filters[0]!.mode).toBe("text");
  });

  it("infers dateRange mode for datetime columns", () => {
    const r = defineResource<ExtTable>(extMeta, {
      columns: (u) => [u.id],
      filters: (u) => [u.createdAt],
    });
    expect(r.filters[0]!.mode).toBe("dateRange");
  });

  it("infers range mode for numeric columns", () => {
    const r = defineResource<ExtTable>(extMeta, {
      columns: (u) => [u.id],
      filters: (u) => [u.priceUsd],
    });
    expect(r.filters[0]!.mode).toBe("range");
  });

  it("infers boolean mode", () => {
    const r = defineResource<ExtTable>(extMeta, {
      columns: (u) => [u.id],
      filters: (u) => [u.archived],
    });
    expect(r.filters[0]!.mode).toBe("boolean");
  });

  it("infers relation mode", () => {
    const r = defineResource<ExtTable>(extMeta, {
      columns: (u) => [u.id],
      filters: (u) => [u.category],
    });
    expect(r.filters[0]!.mode).toBe("relation");
  });

  it("labels filter from the last path segment in TitleCase", () => {
    const r = defineResource<ExtTable>(extMeta, {
      columns: (u) => [u.id],
      filters: (u) => [u.priceUsd, u.createdAt],
    });
    expect(r.filters.map((f) => f.label)).toEqual(["Price Usd", "Created At"]);
  });

  it("rejects non-ColumnRef in the filters selector", () => {
    expect(() =>
      defineResource<ExtTable>(extMeta, {
        columns: (u) => [u.id],
        // @ts-expect-error — deliberate abuse: computed is not a legal filter
        filters: () => [{ id: "x", compute: () => 0 }],
      }),
    ).toThrow(/filters selector must return ColumnRef/);
  });
});

describe("defineResource — actions", () => {
  it("preserves a row action with typed run handler", async () => {
    const run = vi.fn();
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id],
      actions: {
        promote: {
          type: "row",
          label: "Promote",
          icon: "star",
          run,
        },
      },
    });
    expect(r.actions.promote).toBeDefined();
    expect(r.actions.promote!.type).toBe("row");
    if (r.actions.promote!.type !== "row") throw new Error("unreachable");
    await r.actions.promote!.run({
      row: { id: 1, email: "a@b.c", plan: "free", category: null },
      db: null,
      session: null,
    });
    expect(run).toHaveBeenCalledOnce();
  });

  it("keeps stepUp + confirm + disabled on row actions", () => {
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id],
      actions: {
        ban: {
          type: "row",
          label: "Ban",
          confirm: ({ row }) => `Ban ${row.email}?`,
          stepUp: true,
          disabled: ({ row }) => row.plan === "free",
          run: () => {},
        },
      },
    });
    const ban = r.actions.ban!;
    if (ban.type !== "row") throw new Error("unreachable");
    expect(ban.stepUp).toBe(true);
    expect(typeof ban.confirm).toBe("function");
    expect(typeof ban.disabled).toBe("function");
    expect(ban.disabled!({ row: { id: 1, email: "x", plan: "free", category: null } })).toBe(true);
    expect(ban.disabled!({ row: { id: 1, email: "x", plan: "pro", category: null } })).toBe(false);
  });

  it("accepts a bulk action with rows[] context", async () => {
    const run = vi.fn();
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id],
      actions: {
        archive: { type: "bulk", label: "Archive", run },
      },
    });
    const a = r.actions.archive!;
    if (a.type !== "bulk") throw new Error("unreachable");
    await a.run({ rows: [], db: null, session: null });
    expect(run).toHaveBeenCalledOnce();
  });

  it("accepts a bulkEdit action with typed patch", async () => {
    const run = vi.fn();
    const r = defineResource<UserTable>(userMeta, {
      columns: (u) => [u.id],
      actions: {
        changePlan: {
          type: "bulkEdit",
          label: "Change plan",
          fields: ["plan"],
          stepUp: true,
          run,
        },
      },
    });
    const a = r.actions.changePlan!;
    if (a.type !== "bulkEdit") throw new Error("unreachable");
    expect(a.fields).toEqual(["plan"]);
    expect(a.stepUp).toBe(true);
    await a.run({ rows: [], patch: { plan: "pro" }, db: null, session: null });
    expect(run).toHaveBeenCalledOnce();
  });
});
