import { describe, it, expect, vi } from "vitest";
import { z } from "zod";
import { defineFlowPanel, resource } from "../../defineFlowPanel";
import type { ModelMetadata, ResourceAdapter } from "../types";

// ---------------------------------------------------------------------------
// Mock adapter & SQL executor
// ---------------------------------------------------------------------------

const mockSqlExecutor = {
  execute: vi.fn(async () => []),
  transaction: vi.fn(async (fn: (tx: unknown) => Promise<unknown>) => fn({})),
  dialect: "postgres" as const,
  advisoryLock: vi.fn(async () => {}),
  advisoryUnlock: vi.fn(async () => {}),
  advisoryTryLock: vi.fn(async () => true),
  sql: vi.fn(() => ({ text: "", values: [] })),
};

const userMetadata: ModelMetadata = {
  name: "User",
  fields: [
    {
      name: "id",
      type: "int",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: true,
      isAutoGenerated: true,
    },
    {
      name: "email",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "name",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "role",
      type: "enum",
      kind: "enum",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
      enumValues: ["admin", "user"],
    },
    {
      name: "createdAt",
      type: "datetime",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: true,
    },
  ],
  primaryKey: "id",
};

const postMetadata: ModelMetadata = {
  name: "Post",
  fields: [
    {
      name: "id",
      type: "int",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: true,
      isAutoGenerated: true,
    },
    {
      name: "title",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "body",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "published",
      type: "boolean",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "authorId",
      type: "int",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
  ],
  primaryKey: "id",
};

function createMockResourceAdapter(): ResourceAdapter {
  return {
    findMany: vi.fn(async () => ({ data: [], total: 0 })),
    findUnique: vi.fn(async () => null),
    count: vi.fn(async () => 0),
    create: vi.fn(async (_m, args) => args.data as Record<string, unknown>),
    update: vi.fn(async (_m, args) => args.data as Record<string, unknown>),
    delete: vi.fn(async () => ({})),
    getModelMetadata: vi.fn((name: string) => {
      if (name === "User") return userMetadata;
      if (name === "Post") return postMetadata;
      throw new Error(`Unknown model: ${name}`);
    }),
    getEnumValues: vi.fn(() => []),
    getModelNames: vi.fn(() => ["User", "Post"]),
  };
}

const baseConfig = {
  appName: "TestApp",
  timezone: "UTC" as const,
  basePath: "/admin" as const,
  pipeline: {
    stages: ["ingest", "process"] as const,
    fields: { userId: z.string().nullable() },
    stageFields: {},
  },
  security: {
    auth: {
      getSession: async (_req: Request) => null,
    },
  },
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("defineFlowPanel v2 — backward compatibility", () => {
  it("works with plain SqlExecutor (no resources)", () => {
    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: mockSqlExecutor,
    });

    expect(fp.config.appName).toBe("TestApp");
    expect(fp.resources).toBeUndefined();
    expect(fp.resourceAdapter).toBeUndefined();
    expect(fp.queryBuilder).toBeDefined();
    expect(typeof fp.withRun).toBe("function");
    expect(typeof fp.startReaper).toBe("function");
    expect(typeof fp.getDb).toBe("function");
  });

  it("returns schema with appName and no resources when none configured", () => {
    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: mockSqlExecutor,
    });

    const schema = fp.getSchema();
    expect(schema.appName).toBe("TestApp");
    expect(schema.resources).toBeUndefined();
  });
});

describe("defineFlowPanel v2 — with resources (object form)", () => {
  it("resolves resources from object config", () => {
    const mockAdapter = createMockResourceAdapter();

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User", { label: "Users", icon: "users" }),
        posts: resource("Post", { label: "Posts" }),
      },
    });

    expect(fp.resources).toBeDefined();
    expect(Object.keys(fp.resources!)).toEqual(["users", "posts"]);
    expect(fp.resourceAdapter).toBe(mockAdapter);

    // Check resolved user resource
    const userRes = fp.resources!.users;
    expect(userRes.id).toBe("users");
    expect(userRes.modelName).toBe("User");
    expect(userRes.label).toBe("Users");
    expect(userRes.icon).toBe("users");

    // Check resolved post resource
    const postRes = fp.resources!.posts;
    expect(postRes.id).toBe("posts");
    expect(postRes.modelName).toBe("Post");
    expect(postRes.label).toBe("Posts");
  });

  it("auto-generates columns from metadata", () => {
    const mockAdapter = createMockResourceAdapter();

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User"),
      },
    });

    const userRes = fp.resources!.users;
    // Should have auto-generated columns for non-autoGenerated fields
    const colIds = userRes.columns.map((c) => c.id);
    expect(colIds).toContain("email");
    expect(colIds).toContain("name");
    expect(colIds).toContain("role");
    // autoGenerated fields should be excluded
    expect(colIds).not.toContain("id");
    expect(colIds).not.toContain("createdAt");
  });
});

describe("defineFlowPanel v2 — with resources (function form)", () => {
  it("resolves resources from builder function", () => {
    const mockAdapter = createMockResourceAdapter();

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: (fp) => ({
        users: fp.resource("User", { label: "Team Members", icon: "team" }),
      }),
    });

    expect(fp.resources).toBeDefined();
    const userRes = fp.resources!.users;
    expect(userRes.label).toBe("Team Members");
    expect(userRes.icon).toBe("team");
  });
});

describe("defineFlowPanel v2 — schema serialization", () => {
  it("serializes resources for client consumption", () => {
    const mockAdapter = createMockResourceAdapter();

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User", {
          label: "Users",
          access: {
            create: ["admin"],
            delete: false,
          },
        }),
      },
    });

    // With admin role
    const adminSchema = fp.getSchema(["admin"]);
    expect(adminSchema.appName).toBe("TestApp");
    expect(adminSchema.resources).toBeDefined();

    const userSer = adminSchema.resources!.users;
    expect(userSer.id).toBe("users");
    expect(userSer.label).toBe("Users");
    expect(userSer.access.create).toBe(true); // admin has access
    expect(userSer.access.delete).toBe(false); // explicitly denied
    expect(userSer.access.list).toBe(true); // default allowed

    // Without admin role
    const guestSchema = fp.getSchema([]);
    const guestUser = guestSchema.resources!.users;
    expect(guestUser.access.create).toBe(false); // no matching role
    expect(guestUser.access.delete).toBe(false);
    expect(guestUser.access.list).toBe(true);
  });

  it("serialized columns strip functions", () => {
    const mockAdapter = createMockResourceAdapter();

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User", {
          columns: (c) => [
            c.field((p) => p.email),
            c.computed("fullInfo", {
              label: "Full Info",
              compute: (row) => `${row.name} <${row.email}>`,
            }),
          ],
        }),
      },
    });

    const schema = fp.getSchema();
    const userSer = schema.resources!.users;
    expect(userSer.columns).toHaveLength(2);
    expect(userSer.columns[0].id).toBe("email");
    expect(userSer.columns[1].id).toBe("fullInfo");
    expect(userSer.columns[1].type).toBe("computed");
    // No compute function in serialized output
    expect((userSer.columns[1] as Record<string, unknown>).compute).toBeUndefined();
  });
});

describe("defineFlowPanel v2 — adapter detection", () => {
  it("detects { sql, resource } adapter result", () => {
    const mockAdapter = createMockResourceAdapter();

    // Should not throw
    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User"),
      },
    });
    expect(fp.resourceAdapter).toBe(mockAdapter);
  });

  it("throws when resources used with plain SqlExecutor", () => {
    expect(() =>
      defineFlowPanel({
        ...baseConfig,
        adapter: mockSqlExecutor,
        resources: {
          users: resource("User"),
        },
      }),
    ).toThrow("resources require a ResourceAdapter");
  });
});

describe("resource() factory function", () => {
  it("creates a branded descriptor", () => {
    const desc = resource("User");
    expect(desc.__brand).toBe("flowpanel.resource");
    expect(desc.modelRef).toBe("User");
    expect(desc.opts).toEqual({});
  });

  it("creates a descriptor with options", () => {
    const desc = resource("User", { label: "Users", icon: "users", defaultPageSize: 25 });
    expect(desc.opts.label).toBe("Users");
    expect(desc.opts.icon).toBe("users");
    expect(desc.opts.defaultPageSize).toBe(25);
  });
});

describe("defineFlowPanel v2 — resource with actions and computes", () => {
  it("resolves actions and computes into internal maps", () => {
    const mockAdapter = createMockResourceAdapter();
    const banHandler = vi.fn(async () => {});

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User", {
          columns: (c) => [
            c.field((p) => p.email),
            c.computed("displayName", {
              label: "Display Name",
              compute: (row) => String(row.name).toUpperCase(),
            }),
          ],
          actions: (a) => [
            a.mutation({
              label: "Ban User",
              icon: "ban",
              variant: "danger",
              confirm: "Are you sure?",
              when: (row) => row.role !== "admin",
              handler: banHandler,
            }),
          ],
        }),
      },
    });

    const userRes = fp.resources!.users;

    // Computes
    expect(userRes._computes).toBeDefined();
    expect(typeof userRes._computes.displayName).toBe("function");
    expect(userRes._computes.displayName({ name: "alice", email: "a@b.c" })).toBe("ALICE");

    // Actions
    expect(userRes.actions).toHaveLength(1);
    expect(userRes.actions[0].label).toBe("Ban User");
    expect(userRes.actions[0].variant).toBe("danger");

    // Handlers map
    const actionId = userRes.actions[0].id;
    expect(userRes._handlers[actionId]).toBe(banHandler);

    // Whens map
    expect(typeof userRes._whens[actionId]).toBe("function");
    expect(userRes._whens[actionId]({ role: "user" })).toBe(true);
    expect(userRes._whens[actionId]({ role: "admin" })).toBe(false);
  });
});

describe("defineFlowPanel v2 — resource with custom search fields", () => {
  it("resolves custom search fields", () => {
    const mockAdapter = createMockResourceAdapter();

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User", {
          searchFields: [(p) => p.email, (p) => p.name],
        }),
      },
    });

    const userRes = fp.resources!.users;
    expect(userRes.searchFields).toEqual(["email", "name"]);
  });
});

describe("defineFlowPanel v2 — multiple resources with different configs", () => {
  it("resolves each resource independently", () => {
    const mockAdapter = createMockResourceAdapter();

    const fp = defineFlowPanel({
      ...baseConfig,
      adapter: { sql: mockSqlExecutor, resource: mockAdapter },
      resources: {
        users: resource("User", {
          label: "Users",
          defaultPageSize: 25,
          access: { create: ["admin"] },
        }),
        posts: resource("Post", {
          label: "Posts",
          defaultPageSize: 100,
          access: { delete: false },
        }),
      },
    });

    expect(fp.resources!.users.defaultPageSize).toBe(25);
    expect(fp.resources!.posts.defaultPageSize).toBe(100);
    expect(fp.resources!.users.access.create).toEqual(["admin"]);
    expect(fp.resources!.posts.access.delete).toBe(false);
  });
});
