import { describe, it, expect } from "vitest";
import {
  createResourceDescriptor,
  resolveResource,
  inferIncludeFromPaths,
  mergeIncludes,
} from "../resolver";
import type { ModelMetadata } from "../types";

// ---------------------------------------------------------------------------
// Mock metadata
// ---------------------------------------------------------------------------

const mockMetadata: ModelMetadata = {
  name: "Subscription",
  fields: [
    {
      name: "id",
      type: "int",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: true,
      isAutoGenerated: true,
    },
    {
      name: "email",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "status",
      type: "enum",
      kind: "enum",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
      enumValues: ["active", "canceled", "trialing"],
    },
    {
      name: "price",
      type: "float",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "createdAt",
      type: "datetime",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: true,
    },
    {
      name: "updatedAt",
      type: "datetime",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: true,
    },
    {
      name: "userId",
      type: "string",
      kind: "scalar",
      isRequired: true,
      isList: false,
      isId: false,
      isAutoGenerated: false,
    },
    {
      name: "user",
      type: "relation",
      kind: "relation",
      isRequired: false,
      isList: false,
      isId: false,
      isAutoGenerated: false,
      relationModel: "User",
    },
  ],
  primaryKey: "id",
};

// ---------------------------------------------------------------------------
// createResourceDescriptor
// ---------------------------------------------------------------------------

describe("createResourceDescriptor", () => {
  it("returns a branded ResourceDescriptor", () => {
    const descriptor = createResourceDescriptor("Subscription");
    expect(descriptor.__brand).toBe("flowpanel.resource");
    expect(descriptor.modelRef).toBe("Subscription");
    expect(descriptor.opts).toEqual({});
  });

  it("stores opts when provided", () => {
    const descriptor = createResourceDescriptor("Subscription", {
      label: "Sub",
      icon: "credit-card",
    });
    expect(descriptor.opts.label).toBe("Sub");
    expect(descriptor.opts.icon).toBe("credit-card");
  });
});

// ---------------------------------------------------------------------------
// resolveResource — minimal / auto-generated
// ---------------------------------------------------------------------------

describe("resolveResource — auto-generated", () => {
  it("auto-generates columns from non-autoGenerated scalar fields", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);

    const columnIds = resolved.columns.map((c) => c.id);
    // Should include non-autoGenerated scalars + enum fields
    expect(columnIds).toContain("email");
    expect(columnIds).toContain("status");
    expect(columnIds).toContain("price");
    expect(columnIds).toContain("userId");
    // Should NOT include autoGenerated fields
    expect(columnIds).not.toContain("id");
    expect(columnIds).not.toContain("createdAt");
    expect(columnIds).not.toContain("updatedAt");
    // Should NOT include relation fields
    expect(columnIds).not.toContain("user");
  });

  it("auto-generates filters from enum and boolean fields", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);

    const filterIds = resolved.filters.map((f) => f.id);
    expect(filterIds).toContain("status");
    // No booleans in mock — just status
    expect(filterIds).not.toContain("email");
    expect(filterIds).not.toContain("price");
  });

  it("auto-generates searchFields from string scalar fields", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);

    expect(resolved.searchFields).toContain("email");
    expect(resolved.searchFields).toContain("userId");
    expect(resolved.searchFields).not.toContain("price");
    expect(resolved.searchFields).not.toContain("status");
  });

  it("derives label from model name (Title Case)", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.label).toBe("Subscription");
  });

  it("pluralizes label correctly: normal word", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.labelPlural).toBe("Subscriptions");
  });

  it("pluralizes label correctly: word ending in 'y'", () => {
    const descriptor = createResourceDescriptor("Category");
    const meta: ModelMetadata = { ...mockMetadata, name: "Category" };
    const resolved = resolveResource("category", descriptor, meta);
    expect(resolved.labelPlural).toBe("Categories");
  });

  it("pluralizes label correctly: word ending in 's'", () => {
    const descriptor = createResourceDescriptor("Status");
    const meta: ModelMetadata = { ...mockMetadata, name: "Status" };
    const resolved = resolveResource("status", descriptor, meta);
    expect(resolved.labelPlural).toBe("Statuses");
  });

  it("pluralizes label correctly: vowel+y (Day → Days, not Dies)", () => {
    const descriptor = createResourceDescriptor("Day");
    const meta: ModelMetadata = { ...mockMetadata, name: "Day" };
    const resolved = resolveResource("day", descriptor, meta);
    expect(resolved.labelPlural).toBe("Days");
  });

  it("pluralizes label correctly: word ending in 'ch'/'sh'/'x'", () => {
    const r1 = resolveResource("match", createResourceDescriptor("Match"), {
      ...mockMetadata,
      name: "Match",
    });
    const r2 = resolveResource("box", createResourceDescriptor("Box"), {
      ...mockMetadata,
      name: "Box",
    });
    expect(r1.labelPlural).toBe("Matches");
    expect(r2.labelPlural).toBe("Boxes");
  });

  it("sets pagination defaults", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.defaultPageSize).toBe(50);
  });

  it("sets default sort to primaryKey desc", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.defaultSort).toEqual({ field: "id", dir: "desc" });
  });

  it("sets default icon to file-text", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.icon).toBe("file-text");
  });

  it("uses id from key param", () => {
    const descriptor = createResourceDescriptor("Subscription");
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.id).toBe("subscription");
    expect(resolved.modelName).toBe("Subscription");
  });
});

// ---------------------------------------------------------------------------
// resolveResource — shorthand columns (array of PathFns)
// ---------------------------------------------------------------------------

describe("resolveResource — shorthand columns", () => {
  it("resolves shorthand PathFn array to columns", () => {
    const descriptor = createResourceDescriptor<{ email: string; price: number }>("Subscription", {
      columns: [(p) => p.email, (p) => p.price],
    });
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    const ids = resolved.columns.map((c) => c.id);
    expect(ids).toEqual(["email", "price"]);
  });

  it("resolves shorthand PathFn array to filters", () => {
    const descriptor = createResourceDescriptor<{ status: string }>("Subscription", {
      filters: [(p) => p.status],
    });
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.filters[0].id).toBe("status");
  });
});

// ---------------------------------------------------------------------------
// resolveResource — builder columns
// ---------------------------------------------------------------------------

describe("resolveResource — builder columns", () => {
  it("calls column builder function and uses result", () => {
    const descriptor = createResourceDescriptor<{ email: string; price: number }>("Subscription", {
      columns: (c) => [
        c.field((p) => p.email, { label: "Email Address" }),
        c.field((p) => p.price, { format: "money" }),
      ],
    });
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.columns[0].label).toBe("Email Address");
    expect(resolved.columns[1].format).toBe("money");
  });

  it("calls filter builder function and uses result", () => {
    const descriptor = createResourceDescriptor<{ status: string }>("Subscription", {
      filters: (f) => [f.filter((p) => p.status, { label: "Plan Status" })],
    });
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.filters[0].label).toBe("Plan Status");
  });
});

// ---------------------------------------------------------------------------
// resolveResource — actions
// ---------------------------------------------------------------------------

describe("resolveResource — actions", () => {
  it("resolves actions and sets id from builder return", () => {
    const descriptor = createResourceDescriptor<{ email: string }>("Subscription", {
      actions: (a) => {
        const cancel = a.mutation({
          label: "Cancel",
          handler: async () => {},
        });
        cancel.id = "cancel";
        return [cancel];
      },
    });
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(resolved.actions[0].id).toBe("cancel");
    expect(resolved.actions[0].label).toBe("Cancel");
  });

  it("builds _handlers map from actions", () => {
    const handler = async () => {};
    const descriptor = createResourceDescriptor<{ email: string }>("Subscription", {
      actions: (a) => {
        const act = a.mutation({ label: "Do it", handler });
        act.id = "doIt";
        return [act];
      },
    });
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(typeof resolved._handlers["doIt"]).toBe("function");
  });

  it("builds _whens map from actions with when predicate", () => {
    const when = (row: any) => row.status === "active";
    const descriptor = createResourceDescriptor<{ status: string }>("Subscription", {
      actions: (a) => {
        const act = a.mutation({ label: "Act", handler: async () => {}, when });
        act.id = "act";
        return [act];
      },
    });
    const resolved = resolveResource("subscription", descriptor, mockMetadata);
    expect(typeof resolved._whens["act"]).toBe("function");
  });

  it("throws on reserved action ID 'delete'", () => {
    const descriptor = createResourceDescriptor<{ email: string }>("Subscription", {
      actions: (a) => {
        const act = a.mutation({ label: "Delete", handler: async () => {} });
        act.id = "delete";
        return [act];
      },
    });
    expect(() => resolveResource("subscription", descriptor, mockMetadata)).toThrow(/reserved/i);
  });

  it("throws on reserved action ID 'list'", () => {
    const descriptor = createResourceDescriptor<{ email: string }>("Subscription", {
      actions: (a) => {
        const act = a.mutation({ label: "List", handler: async () => {} });
        act.id = "list";
        return [act];
      },
    });
    expect(() => resolveResource("subscription", descriptor, mockMetadata)).toThrow(/reserved/i);
  });

  it("throws on reserved action ID 'create'", () => {
    const descriptor = createResourceDescriptor<{ email: string }>("Subscription", {
      actions: (a) => {
        const act = a.mutation({ label: "Create", handler: async () => {} });
        act.id = "create";
        return [act];
      },
    });
    expect(() => resolveResource("subscription", descriptor, mockMetadata)).toThrow(/reserved/i);
  });
});

// ---------------------------------------------------------------------------
// inferIncludeFromPaths
// ---------------------------------------------------------------------------

describe("inferIncludeFromPaths", () => {
  it("scalar path produces empty include", () => {
    expect(inferIncludeFromPaths(["email"])).toEqual({});
  });

  it("single relation path produces include true", () => {
    expect(inferIncludeFromPaths(["user.email"])).toEqual({ user: true });
  });

  it("nested relation path produces nested include", () => {
    expect(inferIncludeFromPaths(["user.subscription.planId"])).toEqual({
      user: { include: { subscription: true } },
    });
  });

  it("_count paths are skipped", () => {
    expect(inferIncludeFromPaths(["_count.posts"])).toEqual({});
  });

  it("merges duplicate relations", () => {
    const result = inferIncludeFromPaths(["user.email", "user.name"]);
    expect(result).toEqual({ user: true });
  });

  it("merges nested and flat for same relation", () => {
    const result = inferIncludeFromPaths(["user.email", "user.subscription.planId"]);
    expect(result).toEqual({ user: { include: { subscription: true } } });
  });

  it("handles multiple different relations", () => {
    const result = inferIncludeFromPaths(["user.email", "plan.name"]);
    expect(result).toEqual({ user: true, plan: true });
  });
});

// ---------------------------------------------------------------------------
// mergeIncludes
// ---------------------------------------------------------------------------

describe("mergeIncludes", () => {
  it("returns inferred when manual is empty", () => {
    const inferred = { user: true };
    expect(mergeIncludes(inferred, {})).toEqual({ user: true });
  });

  it("manual wins on conflict", () => {
    const inferred = { user: true };
    const manual = { user: { include: { posts: true } } };
    const result = mergeIncludes(inferred, manual);
    expect(result).toEqual({ user: { include: { posts: true } } });
  });

  it("merges non-conflicting keys", () => {
    const inferred = { user: true };
    const manual = { plan: true };
    expect(mergeIncludes(inferred, manual)).toEqual({ user: true, plan: true });
  });

  it("manual undefined produces inferred", () => {
    const inferred = { user: true };
    expect(mergeIncludes(inferred, undefined)).toEqual({ user: true });
  });
});
